### ISSUE TITLE
ClassPath isn't a Haxelib!

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/intellij-haxe#100]
Works on a [latest build](https://github.com/TiVo/intellij-haxe/blob/314e4e87dd12e8e2f18893cf105c04b5ef7f382e/intellij-haxe.jar).

After indexation of opened project we can see two libs automatically added as dependencies. But it's not from `-lib ...` from build.hxml ! This is `-cp` Classpaths.
![screen shot 2015-01-11 at 17 29 08](https://cloud.githubusercontent.com/assets/888526/5695497/85fe1c36-99b8-11e4-9a24-bcb80fe16e15.png)
![screen shot 2015-01-11 at 17 38 02](https://cloud.githubusercontent.com/assets/888526/5695514/be35386e-99b8-11e4-969d-6870a8fc603b.png)
![screen shot 2015-01-11 at 17 38 38](https://cloud.githubusercontent.com/assets/888526/5695516/c32f8932-99b8-11e4-83bd-fa3da1296667.png)

Linked hxml:

``` hxml
-cp src
-cp tests
-main Main
-lib signal
-dce full
--each
-x out/tests/main
```

TIR: STB-7318

**Comment by as3boyan** [comment]
Ok, thanks, src should be resolved relative to project root directory, but first, we need to make sure that it's not already added.

**Comment by EBatTiVo** [comment]
There is code in place to deal with the "already added" case, though I guess it could be broken.  In this case, we should NOT be adding libs that come from the classpath at all.  As I remember, all of the libraries that we add come from calling the haxelib command.  We don't add them from any other configuration file.  Could haxelib be presenting us libraries from the classpath?

**Comment by fzzr-** [comment]
Again. [Release 0.9.5](https://github.com/TiVo/intellij-haxe/releases/tag/0.9.5) on Idea 14 Community Edition (14.1.4)

![hx-plugin-cp-bug mov opt](https://cloud.githubusercontent.com/assets/888526/8745420/607806d0-2c88-11e5-9448-a17469843114.gif)

**Comment by as3boyan** [comment]
It doesn't seem to check project paths.

**Comment by eliasku** [comment]
+1
Very critical!

**Comment by eliasku** [comment]
@as3boyan @EBatTiVo ClassPath should be not added as EXTERNAL libraries!!! ClassPath should be marked by user in module configuration. Adding `-cp` as libraries is wrong behaviour.

**Comment by EricBishton** [comment]
Fixed a while ago and no further action appears to be required.  Closing.
