### ISSUE TITLE
Inline keyword not supported with extern functions.

### ISSUE THREAD

**Issue by derRaab** [HaxeFoundation/intellij-haxe#1012]
I updated to the new version 1.3 an now`Browser.console` is marked a `Unresolved symbol`:
<img width="301" alt="Bildschirmfoto 2020-09-08 um 15 12 46" src="https://user-images.githubusercontent.com/2079540/92481002-f943db00-f1e5-11ea-890e-c3d8b34d986c.png">

So I checked the `Browser` class included in Haxe 4.1.3 and it looks like the Plug-in doesn't like the `inline` syntax:
<img width="682" alt="Bildschirmfoto 2020-09-08 um 15 18 15" src="https://user-images.githubusercontent.com/2079540/92481363-8b4be380-f1e6-11ea-93b4-b8bf861fbcf0.png">

I'm using Intellij IDEA 2020.2.1 now but it also happend in 2020.1.4.

**Comment by EricBishton** [comment]
`extern inline` seems like an oxymoron to me, but it seems to be common in Std for newer releases.  This shouldn't be too difficult to fix.

**Comment by derRaab** [comment]
Thanks! :)

**Comment by EricBishton** [comment]
I've created patch release 1.3.1 with this fix in it.
