### ISSUE TITLE
Non-standard Error Highlighting Declaring New Functions

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#1023]
It's a bit distracting when I start writing a function and it highlights all the code below that instead of just underlining at the source line. I haven't ever seen this before in IntelliJ IDEs. The highlighted text has a pop-up tip that reads "un-parseable code"

![image](https://user-images.githubusercontent.com/45294513/94329498-84b0c080-ff89-11ea-832c-a48b71cc2ddc.png)

Here's how they do it in Java, just a little underline where something more is expected:

![image](https://user-images.githubusercontent.com/45294513/94329534-c6da0200-ff89-11ea-9bc0-83a026e871a3.png)

**Comment by EricBishton** [comment]
The primarily motivation for the feature is to indicate why activity and changes that occur in a region don't have proper functionality: Things like Go To Definition (F4), and Refactorings, and Parameter Affordance (Ctrl+P).  Also note that there _is_ a tiny red line at the point at which the parser detects the error.  The highlighting follows the red line, usually immediately, but sometimes later, as in the first image posted above.

That said, if it is annoying to you (and I understand that it is for some people), it is easily disabled:  Use the settings dialog to edit the Haxe color scheme (File->Settings: Editor > Color Scheme > Haxe), select the "Unparseable Data" line, and deselect the check boxes.

![image](https://user-images.githubusercontent.com/12093217/94332391-ae69e780-ff89-11ea-8e98-c090a67be2c8.png)

**Comment by CanIGetaPR** [comment]
Should probably fix #1024 , and that will fix this.

**Comment by CanIGetaPR** [comment]
You know what it's like a race now, if I type out the declaration quickly enough the highlighting doesn't happen. It only happens when I stutter. ;)

**Comment by EricBishton** [comment]
> It only happens when I stutter. ;)

😄 

One thing is for sure: It lets you know what the parser is having issues with.  Most folks wonder what this is at first, and once they figure it out, quickly get used to it and/or change the colors so that it's not as distracting to them.  (And the colors I picked as default aren't distracting to _me_.)  I don't know of anybody who has totally disabled the feature once they understood it, but I'm sure there are some who have.
