### ISSUE TITLE
Autocomplete confused when a function type parameter has one argument

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#1027]
### Here it is displaying the iterator option **correctly**:

![image](https://user-images.githubusercontent.com/45294513/94368428-f7b55680-00b1-11eb-84b1-c2770d49a0ec.png)

### Here it is being confused and making the return type be an argument, when there's only one argument for the function:

![image](https://user-images.githubusercontent.com/45294513/94368458-31865d00-00b2-11eb-81fe-a4305bd1dbb7.png)

![image](https://user-images.githubusercontent.com/45294513/94368474-406d0f80-00b2-11eb-8da6-ddf9cf5c3eb6.png)

### It displays sort of correctly if brackets are inserted around the argument, however please note _**this is invalid Haxe**_:

![image](https://user-images.githubusercontent.com/45294513/94368531-75796200-00b2-11eb-8850-eb6cd2ab0c96.png)

**Comment by EricBishton** [comment]
I have a sneaking suspicion that `()->Void` is being parsed as a lambda, and not a function type specification.

**Comment by CanIGetaPR** [comment]
Keep in mind `()->Void` and `Int->Void` result in the same type of bugged output.

**Comment by m0rkeulv** [comment]
closing this one as it looks like a fix has been merged.
