### ISSUE TITLE
Does not recognize the final keyword in interfaces as not needing immediate intialization

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#1028]
Haxe compiles it fine with a final keyword on the property, but the IDE complains about this final member not being initialized in the interface.

![image](https://user-images.githubusercontent.com/45294513/94735285-81765580-0338-11eb-92ab-3eaeeba869ee.png)

**Comment by m0rkeulv** [comment]
@EricBishton  this is solved in develop now

![image](https://user-images.githubusercontent.com/3193925/97204781-d2059500-17b6-11eb-89f1-f87d62558e56.png)

**Comment by EricBishton** [comment]
Good.  It will be available in release 1.4, then.
