### ISSUE TITLE
Implementing Class Doesn't Show an Error for Not Implemented Variables

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#1029]
### Problem: There's no underline on BaseTheme even though it fails to implement the variables field1 and field2 from ITheme.

![image](https://user-images.githubusercontent.com/45294513/94735531-e5991980-0338-11eb-9767-1033bc02f4de.png)

ITheme interface showing field1 and field2 properties:

![image](https://user-images.githubusercontent.com/45294513/94735601-006b8e00-0339-11eb-9e91-794f17464ad7.png)

Here is the compiler error stating BaseTheme cannot be compiled because the fields field1 and field2 are missing:

![image](https://user-images.githubusercontent.com/45294513/94735750-36a90d80-0339-11eb-8241-9f22f077d657.png)

**Comment by EricBishton** [comment]
PR#1036 is merged and fixes this.
