### ISSUE TITLE
Wrong behavior for "Class 'Foo' is never used" in abstracts

### ISSUE THREAD

**Issue by boozook** [HaxeFoundation/intellij-haxe#107]
Plugin version: [latest build](https://github.com/TiVo/intellij-haxe/blob/314e4e87dd12e8e2f18893cf105c04b5ef7f382e/intellij-haxe.jar).

![screen shot 2015-01-11 at 19 19 54](https://cloud.githubusercontent.com/assets/888526/5695915/a16f5592-99c8-11e4-9793-668340b11d05.png)

Full source for reproduce:

``` haxe
package ;
class Demo {
    public static function main() { }
}

private class Foo
{
    public var a:Int;
    public var b:Int;
    public function new(){}
}

@:forward
private abstract Bar(Foo) from Foo to Foo
{
    public function new()
    {
        this = new Foo();
        a = 1;
        b = 2;
    }
}
```

TIR: STB-7322

**Comment by EBatTiVo** [comment]
I see a comment about from/to just prior to the ``` abstractClassDeclaration ``` in the haxe.bnf, but they're not part of the (or any) rule.

**Comment by EBatTiVo** [comment]
Related to #78.  Probably the same solution.

**Comment by m0rkeulv** [comment]
Test with latest does not show warning, so i am closing this one.
![image](https://github.com/user-attachments/assets/2b0fc441-8175-49f1-bfe9-e26fb65e97c9)

**Comment by boozook** [comment]
Wow 😮 10 years ago it was. Great, thanks! 😊
