### ISSUE TITLE
Event listeners expect return type Dynamic->Void instead of Void

### ISSUE THREAD

**Issue by Beckwahn** [HaxeFoundation/intellij-haxe#1080]
Plugin version: Beta build (e6846b6c)
IDEA version: 2020.3.2 Community Edition & 2020.3.2 Ultimate trial version
OS: Mac OS Big Sur (11.2.1)
JDK: 1.8.0_161

Happens to all listeners, tested in several projects:

![return_value](https://user-images.githubusercontent.com/60543387/108888030-3fadba80-760b-11eb-9a09-40e3fbdc2206.jpg)

**Comment by EricBishton** [comment]
Thanks for the report!

**Comment by m0rkeulv** [comment]
Fixed in 1.4.1
