### ISSUE TITLE
Incompatibility with 2021.1

### ISSUE THREAD

**Issue by Sartoric** [HaxeFoundation/intellij-haxe#1083]
After upgrading to 2021.1, the plugin isn't working anymore

`Plugin error: Plugin 'Haxe Toolkit Support' (version '1.3.1 for IDEA 2020.x') is not compatible with the current version of the IDE, because it requires build 205.* or older but the current build is IU-211.6693.111`

**Comment by EricBishton** [comment]
The plugin is marked as compatible with 2020.x versions of IDEA.  We need to build and test against 2021.

For those who may want to try their hand at it: The .../build.gradle file has to be updated (findSdkValuesAndProperties()) and a new .../properties/idea_v21.properties file created (modified version of .../properties/idea_v20.properties).

This will be a bit tougher than just updating properties, though, because Java11 is required for IDEA 2020.3+ and there are compatibility complaints to be dealt with.

**Comment by Borman2000** [comment]
Any updates on this issue?

**Comment by m0rkeulv** [comment]
The Develop branch should be able to build for 2021.1.
You can also download the  pre-replase/beta build here:
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202104151903

**Comment by Sartoric** [comment]
@m0rkeulv 
I'm testing the pre-release but it doesn't seems to do much.
It's not even formatting the code. Am I missing something ?

**Comment by Gama11** [comment]
@Sartoric What IntelliJ version are you testing it against? The pre-release build is for 2021.1, but the current IJ version is 2021.2.

**Comment by Sartoric** [comment]
@Gama11 
oh, yes, you're right, I didn't noticed that.
I'm on 2021.2

I'll downgrade and I'll try again

**Comment by Sartoric** [comment]
@Gama11 
I have the same using 2021.1.3 (can't go back to 2021.1)
I tried to invalidate the cache too

**Comment by iirekm** [comment]
the same with 2021.2.3, simple updating version in plugin.xml doesn't help

**Comment by imcasper** [comment]
I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1.
If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

**Comment by m0rkeulv** [comment]
I am interested!

**Comment by barisyild** [comment]
I am also interested!

**Comment by ansien** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1. If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

Very interested!

**Comment by Deirel** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1. If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

It would be very helpful!

**Comment by backda** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1. If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

Pleasee!!

**Comment by Mikael91k** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1. If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

Do it! Just do it! Make our dream come true! :D

**Comment by vasilykosmosgames** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1.
> If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

Very interested!

**Comment by William-Leonard** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1. If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

Interested 🙏

**Comment by ghost** [comment]
> I made a lot of improvements on this plugin. Including support for all versions of the idea up to 2022.1. If more than one and a half people are interested, I will try to promote the publication of the repository in my company.

I'm also very interested in this. I hope you succeed in publishing the code.

**Comment by masqueanthony** [comment]
Thanks for your offer to release your updates @imcasper! Our company has supported this effort in the past and would happily do a small donation or patreon if it helps to keep this project alive.

**Comment by mallyskies** [comment]
Thanks for your offer to release your updates @imcasper! Our company has supported this effort in the past and would happily do a small donation or patreon if it helps to keep this project alive.

**Comment by Deirel** [comment]
@imcasper Hi, do you have any updates?

**Comment by ByteAtATime** [comment]
Does this update plan to be released? IntelliJ is better than VSCode (imo).

**Comment by Frontrider** [comment]
I'm really interested in this. I have a tool in my hands where developing it now would mean swapping between at least 2, if not 3 "text editors".

**Comment by imcasper** [comment]
Unfortunately, the company where I worked on the plugin has still not given permission to publish the code.
In principle, I could find the time and independently support the new version if there is a sponsor.

**Comment by rosingrind** [comment]
Look up #1097 for updates, you can even build it yourself now

**Comment by barisyild** [comment]
Issue fixed you can download latest version of plugin from releases, please close issue
