### ISSUE TITLE
Issue with optional fields in typedef

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/intellij-haxe#1087]
![image](https://user-images.githubusercontent.com/1607138/121839232-4eb39800-cce2-11eb-8f1f-348d34697084.png)

since Haxe 4.0.0
A structure field can be declared as optional in the class notation by prefixing its name with a question mark ?:

https://haxe.org/manual/types-structure-optional-fields.html

**Comment by m0rkeulv** [comment]
this should be fixed on the dev branch, i tested on my machine now and to me it looks fine.
![image](https://user-images.githubusercontent.com/3193925/122052337-dd5d0d80-cde5-11eb-9572-ff4a9411c585.png)

you could try the beta/pre-release builds and see if it is solved.
https://github.com/HaxeFoundation/intellij-haxe/releases

**Comment by CrazyFlasher** [comment]
yes, works fine, thanks!
