### ISSUE TITLE
Showing error for using subclass with templated classes

### ISSUE THREAD

**Issue by ljurow** [HaxeFoundation/intellij-haxe#1093]
var atask:ATask = new ObjectTask();
The Haxe plug in show the error "Incompatible type: ObjectTask should be ATask" even though it's not a haxe compile error

ATask is just a simple class, but ObjectTask is defined this way:
class ABObjectTask<A,B> extends ATask { 
  public function new(object1:A, object2:B)
}
typedef ObjectTask = ABObjectTask<Any,Any>;

**Comment by m0rkeulv** [comment]
i am unable to reproduce this problem in 1.4.2, i guess this is solved ?
```haxe
package ;
class Issue_1093 {
    public function new() {
        var atask:ATask = new ObjectTask();
    }
}

class ATask {
}

class ABObjectTask<A, B> extends ATask {
    public function new(object1:A, object2:B) {

    }
}

typedef ObjectTask = ABObjectTask<Any, Any>;
```
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/8dff0b58-a355-4cb3-b6ff-91171220ed7b)
