### ISSUE TITLE
 Type mismatch error in filter function with typed argument

### ISSUE THREAD

**Issue by alexk74** [HaxeFoundation/intellij-haxe#1098]
For the filter function it shows a type mismatch if argument n is typed.
> 
> ```
> var list:Array<Int> = [1,2,3,4];
> list = list.filter((n:Int) -> n%2 == 0);
> //Error:Type mismatch (Expected: 'T->Bool' got: 'Int->Bool')
> ```

That's a separate bug entirely, having to do with the internal (Haxe) type resolver.  Please file it separately. Thanks.

_Originally posted by @EricBishton in https://github.com/HaxeFoundation/intellij-haxe/issues/1097#issuecomment-1491381924_

**Comment by m0rkeulv** [comment]
Tested with current dev branch and i dont get this error, so i expect this to work with current release (1.4.1)  or at least in the next release (1.4.2)
