### ISSUE TITLE
Standard library not found

### ISSUE THREAD

**Issue by ROCK201888** [HaxeFoundation/intellij-haxe#1112]
Haxe 4.3.1
Haxelib 3.3.0
openfl 9.2.1

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/113576910/8734ad61-d7f4-46b9-a91d-b32e2c0b6688)

windows x64

**Comment by EricBishton** [comment]
That looks like Haxe hasn't been set up correctly.  The HAXE_STD_PATH variable in must be set before lime will work at all.  Ensure that you have followed the Haxe and Lime installation instructions and that you can run that test from a command shell before trying to use the Haxe Plugin and IntelliJ IDEA.

The global environment must be set up before starting IntelliJ IDEA from Windows Explorer.  Or, it can be set inside of a shell, if  IntelliJ IDEA is started from the command line.

**Comment by ROCK201888** [comment]
i fix it. but: 
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/113576910/9bb8eb2e-1b20-4135-b163-c69d03c7a242)

**Comment by EricBishton** [comment]
That's a C++ compiler issue. (The __declspec macro isn't defined.)  I have no idea why Lime is expecting you to have a C++ compiler set up correctly, but this is definitely outside of the plugin's purview.  I suggest you post the error or a question on the Lime repo https://github.com/openfl/lime or their forums http://community.openfl.org/c/lime.
