### ISSUE TITLE
Can't install in android studio

### ISSUE THREAD

**Issue by CodestarGames** [HaxeFoundation/intellij-haxe#1117]
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/5861090/693bfc62-2476-4da2-bf47-f5a1425e4c2d)

My android studio version is 

Android Studio Flamingo | 2022.2.1 Patch 2

**Comment by m0rkeulv** [comment]
i was expecting android studio to be over on 2023 releases by now, so i have replaced and upgraded API calls in the current code base, some of these are not in  the 2022 versions, so i cant build the plugin for 2022 without reverting  code.

the plugin should work with  `Android Studio Hedgehog 2023.1.1` but its still in Canary  testing it seems, hopefully it will be released soon. if its not a deal breaker for you you could try to use it with  Android Studio Hedgehog

https://developer.android.com/studio/preview

**Comment by m0rkeulv** [comment]
latest release should be compatible with Android Studio Giraffe RC1.

**Comment by m0rkeulv** [comment]
Android Studio Giraffe is now the current release and 1.4.13 should support it, so ill close this issue for now.
