### ISSUE TITLE
anonymous structures does not parsing

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1131]
anonymous structures does not parsing

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/5a6986d4-e0d3-4462-8897-1eb288b80ca0)

**Comment by m0rkeulv** [comment]
Try latest beta build and see if it solves your issue, it seems to mostly work for me. 

Only thing i can see that might not work 100% is when anonymous structure use type parameter with constraints and you want to use that constraint/known properties  in your method implementation.

https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202308040044

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/a1036b7b-3395-4dbc-a2d4-78731f992574)

**Comment by barisyild** [comment]
It looks like the problem is solved!
