### ISSUE TITLE
Alt + Enter auto-import not displaying

### ISSUE THREAD

**Issue by guruas3** [HaxeFoundation/intellij-haxe#1132]
First of all thanks for continuing with the development of this plugin with newer Intellij versions.

I finally switched from Intellij 2018 to 2023, but Alt + Enter doesn't show auto-import intention.

Here are 2 screenshots between these 2 versions.

![auto-completion-intellij2018](https://github.com/HaxeFoundation/intellij-haxe/assets/981231/fd7532f5-4f00-40b1-8763-f00deffc28db)
<img width="632" alt="auto-completion-intellij2023" src="https://github.com/HaxeFoundation/intellij-haxe/assets/981231/64e47a1e-2247-46a0-baea-58d047d4cd5d">
<img width="429" alt="complete-intellij2023" src="https://github.com/HaxeFoundation/intellij-haxe/assets/981231/ed776ebd-ab52-46a3-ae04-1c4603e4330c">

All the settings between these 2 versions should be the same.
Dependencies in project module and SDK are set up properly.

Do i miss something or is it a bug?

Versions i'm using:

IntelliJ IDEA 2023.2 (Ultimate Edition)
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains
Haxe Toolkit Plugin 1.4.11
Haxe 4.2.5
Windows 11

**Comment by m0rkeulv** [comment]
found the bug and fixed it (i think). you can test out  this beta build and see if it solves your problem
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202308071839

note that you will probably get an error the first time you open a list  of classes you can import if your using 2023.2, just ignore it for now, i cant fix it without breaking backwards compatibility  as the class jetbrains want me to switch to does not exist in 2023.1.x

**Comment by guruas3** [comment]
Awesome. It works now! Thank you

You mean this error?

```
Error evaluating expression type for element ARRAY_ACCESS_EXPRESSION "params[0]":params[0]:HaxeArrayAccessExpressionImpl
  
  java.lang.NullPointerException: Cannot invoke 

"com.intellij.plugins.haxe.lang.psi.HaxeClass.findArrayAccessGetter(com.intellij.plugins.haxe.model.type.HaxeGenericResolver)"
because the return value of "com.intellij.plugins.haxe.model.type.SpecificHaxeClassReference.getHaxeClass()" is null
```

**Comment by m0rkeulv** [comment]
Thats a different error than the one i was thinking of, i guess i might have forgotten a null check :D
