### ISSUE TITLE
Module-level vars highlighted as errors

### ISSUE THREAD

**Issue by ilevd** [HaxeFoundation/intellij-haxe#1135]
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/5524072/be942371-2b33-4507-9c62-8903006f75f2)

**Comment by m0rkeulv** [comment]
i guess its the private keyword, ill look into what keywords are allowed for Module-level members

**Comment by ilevd** [comment]
@m0rkeulv, without private it's highlighted too.

**Comment by m0rkeulv** [comment]
do you have `package` as your first line ?

**Comment by m0rkeulv** [comment]
i am building a beta build now, as far as i can tell it should not complain anymore in (1.4.14 beta)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/1d7976d6-2f05-457c-8a27-aafcb4bc51cb)

**Comment by ilevd** [comment]
> do you have `package` as your first line ?

No, but with it it's highlighting anyway.

> i am building a beta build now, as far as i can tell it should not complain anymore in (1.4.14 beta)

Nice!

**Comment by m0rkeulv** [comment]
try this one and see if it fixes your issue:
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202309221605

**Comment by ilevd** [comment]
It works now.
