### ISSUE TITLE
Abstract class with partial implementation of interface is highlighted as error

### ISSUE THREAD

**Issue by ilevd** [HaxeFoundation/intellij-haxe#1136]
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/5524072/3dbc27cb-bf4c-4243-b5d8-2c714014e5b8)

**Comment by m0rkeulv** [comment]
ill try to get this fixed later today or tomorrow, the syntax highlighting is easy to fix but i found a few other bugs while testing that i want fix together with this one.

**Comment by m0rkeulv** [comment]
Here's a new beta build that should fix this one
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202309232235

**Comment by ilevd** [comment]
Thanks!
