### ISSUE TITLE
Xor operator is highlighted as error

### ISSUE THREAD

**Issue by ilevd** [HaxeFoundation/intellij-haxe#1137]
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/5524072/0451465b-7131-4c22-a703-5014d3ba09f7)

**Comment by m0rkeulv** [comment]
fixed in this release:
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/pre-release%2F202309241107

**Comment by ilevd** [comment]
Nice!
