### ISSUE TITLE
Haxelib Autocomplete Instructions No workie

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#1140]
I tried to follow these instructions:

```
Auto Complete For Haxelibs

    Navigate to File -> Project Structure -> Modules -> Dependencies
    Click the + to Add a new Library of type Haxe.
    Select the folder that contains haxelib.json

For example, to enable auto complete for OpenFl 9.0.2, the folder with haxelib.json is located at HaxeInstallPath/haxe/lib/openfl/9,0,2 
```

Unfortunately they don't work. 

# Work-around:

Auto Complete For Haxelibs

    Navigate to File -> Project Structure -> Modules -> Dependencies
    Click the + to Add a new Library of type Haxe.
    Select the folder that contains the top level source packages
    If IDEA can't determine what kind of files the chosen item contains, choose Library Classes
    For configure choose Project Library.

For example, to enable auto complete for OpenFl 9.3.2, the folder with the top level source packages is located at HaxeInstallPath/haxe/lib/openfl/9,3,2/src

**Comment by CanIGetaPR** [comment]
Whoops I was looking at the master branch and funnily enough those were some instructions I created too!

https://github.com/HaxeFoundation/intellij-haxe/commit/5eb82c1197216e84be6217c948fa5b32a25c047e

**Comment by CanIGetaPR** [comment]
Is this way I found the correct way for adding haxelib auto complete or is there a better way?

**Comment by andreibaca** [comment]
I can confirm this issue and it's not only autocomplete it does not see the imported classes at all. 
The workaround seems to work. But for me this issue exists only with newer libraries.
Older openfl and flixel libraries seem to work as before.

**Comment by m0rkeulv** [comment]
i would recommend using a  build system file instead of manually adding libs, it could be that the auto import from the build systems part of the code cause some issues or some of the resent changes in intellij. ill have to do some debugging to figure out why manually libs are not not added  correctly to the project.

**Comment by m0rkeulv** [comment]
when adding libraries manually, are you sure you added the paths as `Classes`and  not `Sources` ?
i can reproduce the problem by only adding sources and not classes.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/fee1a46f-a877-4dfc-b07a-52be75f7831c)

**Comment by andreibaca** [comment]
Usually I am adding both classes and sources.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/75330721/5dfd076a-ba08-4263-a554-af23dc173ec4)

Regarding the build system file. I am using openfl that builds with lime so I am using Project.xml for project setup.
Never built a haxe project differently - so I don't even know how to do it.

An important detail - I am using lix to manage haxe versions and libraries.

**Comment by m0rkeulv** [comment]
not sure how lix handles things,  with haxelib  all you really need to do is add the project XML and intellij would detect and setup things for you.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/eeb1524f-d1a7-42f6-8da6-2ca33ce96f27)

but if you want to use lix i guess you will have to  add them manually,  make sure gobal libs are also added to your modules dependencies.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/82d50858-cecd-4547-b7ed-fd12bc0c98b9)

**Comment by m0rkeulv** [comment]
I did some manual testing, and while the GUI was a bitt buggy with global lib names it should work just fine adding libs manually.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/b91c90ce-3f76-4408-a510-584eba85071d)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/a53f154c-8c9c-493b-8d4e-b75a56e23e90)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/6ab96b87-c2ac-4de9-bcec-b2df37961af0)
