### ISSUE TITLE
Weird inspection errors

### ISSUE THREAD

**Issue by Kyliathy** [HaxeFoundation/intellij-haxe#1147]
I've updated to 1.4.30, invalidated caches & restarted.

But I'm getting a lot of inspection errors, even for core Haxe types:

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/dfa957b7-5e4c-425c-828a-5a1e0fa50d5a)

Or for generic types:

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/5a0142b9-be46-4050-991c-3bed75b14d81)

Signature of that function is: 

```
	static public function filterQT<T: QuarxTaggable> (items: Array<T>, filters: Array<CollectionFilterI>,
			filterPolicy: FilterPolicy, owner: QuarxTaggable = null, useIgnoredTags: Bool = false,
			postFilterFunction: (T, QuarxBase) -> Bool = null): Array<T>
```

So it should work, because I'm passing it Array<NNDataScenery>()

Another example, similar to the one above, which again shows that it expects CollectionTypes when in fact it's an Array of something. So it seems like something's up with Arrays :)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/bc9d2b61-3530-4256-b029-5ad9d2e008ad)

**Comment by m0rkeulv** [comment]
have you configured the SDK ?  you will get lots of errors if it cant find the classes from the SDK.

**Comment by Kyliathy** [comment]
Yeap, all looks good to me. And there's not THAT many errors :). Seems like most of them are about Arrays. (Thank you for answering and have a nice weekend).

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/cd2063ef-e3be-4e92-85a8-da469321efa7)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/64b957f2-bbe5-4a51-be93-d81cc2dea35d)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/739d2928-bd4f-45ea-a4e0-0865d57db28c)

**Comment by m0rkeulv** [comment]
if you navigate  to type on that Array(Ctrl click). 
Do you get to the SDK Array class or does it take you to a different class or Enum value ?
my best guess is that the plugin is resolving Array to the wrong type

the signatures seems fine on my machine,so its probably other classes that confuses the plugin.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/137f4600-784c-402f-8430-35e805d38abc)

**Comment by m0rkeulv** [comment]
think i might have reproduced your problem with an enum value
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/fe51a665-db80-4bb7-87ad-f9fe137e10c4)

**Comment by barisyild** [comment]
I think it's the same problem.

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/2f902d64-3cd8-43c0-b8c8-a9b332e381be)

**Comment by m0rkeulv** [comment]
Not sure how you got that error, works fine when i try with 1.4.30, what are your defines and what version of the plugin is this ?

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/350745d3-1a09-4dd8-a103-745feb6d9480)

**Comment by Kyliathy** [comment]
@m0rkeulv  you're right, when I go to definition, it takes me to this Enum that I have in my project:

```
package my.app.package.path;

enum CollectionTypes
{
	Hierarchical;
	Array;
	Mixed;
}
```

This should of course not happen because nowhere am I importing CollectionTypes in that file, and even if I were, Haxe should compile-error me if there's any type confusion (and there isn't) :).

**Comment by m0rkeulv** [comment]
made a fix yesterday that i think solves this problem. (https://github.com/HaxeFoundation/intellij-haxe/commit/e608a74a6570d46a84a16e8346805200930bb25e) it will be in the next release.

**Comment by trnzk** [comment]
The same issue occurs when `enum abstract` is used, do you have a chance to fix this as well?

**Comment by m0rkeulv** [comment]
Let me know if this release fixes any of the issues.
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.31

**Comment by trnzk** [comment]
Thanks for the new version; it resolves some cases, but there are still situations where it uses enum values, as in the example below.

![order](https://github.com/HaxeFoundation/intellij-haxe/assets/11985154/f6f0fbdd-0554-4c97-b18f-d8893607f778)

**Comment by m0rkeulv** [comment]
Can you check if this one fixes this problem
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.32

**Comment by trnzk** [comment]
Thank you, the above example has been fixed, but there is one more thing: If the enum E is in a separate file, it still cannot correctly detect A.

A.hx
```
package a;

class A
{
  public var f : Int;
}
```

E.hx
```
package a;

enum abstract E(Int)
{
  var A;
  var B;
}
```

Main.hx
```
import a.A;
import a.E;

class B extends A
{
  var g : Int = 0;
}

class Main
{
  static public function main()
  {
    var b = new B();
    b.f = 1;
  }
}
```

**Comment by m0rkeulv** [comment]
i think this one (1.4.33) should fix the resolver problem.
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.33

**Comment by trnzk** [comment]
I checked the project I'm working on, and it seems like the problem has been resolved. I did not encounter any errors. It was a frustrating issue, constantly requiring name changes. It's great that it's resolved. Thank you...
