### ISSUE TITLE
error Conditional Compilation

### ISSUE THREAD

**Issue by ericfillipe1** [HaxeFoundation/intellij-haxe#115]
![haxe](https://cloud.githubusercontent.com/assets/4976223/6014386/f908cd6e-ab49-11e4-85e9-96c27ec081fb.png)

https://github.com/HaxeFoundation/hscript/blob/master/hscript/Bytes.hx

TIR: STB-7325

**Comment by EBatTiVo** [comment]
We've seen this as part of Issue #29.  The current parser strategy is to ignore the preprocessing tokens and expect the rest of the code to be correct.  This is wrong in a number of cases.  However, trying to ignore one half or the other (before or after the #else), also leads to errors with completion, import statements, refactoring, and other places.

**Comment by EBatTiVo** [comment]
BTW, on build 0.8.1.1.TiVo.ClassHierarchy.11, the error is "expected [...] got ;"

**Comment by mayakwd** [comment]
Already fixed

**Comment by EricBishton** [comment]
Released in 0.11.0
