### ISSUE TITLE
Can't use String type in generics

### ISSUE THREAD

**Issue by Kyliathy** [HaxeFoundation/intellij-haxe#1151]
I'm using 1.4.38 and everything _almost_ works. Except that any Generic type that uses String is underlined:

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/20860173/e8969b3b-67b2-4f62-b1ef-ac5136d99fce)

**Comment by m0rkeulv** [comment]
does it resolve the String class at all ?  

i cant really see a way to reproduce it.
With the SDK everything is fine
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/8cee3dbf-1809-4635-a474-c1f5efb30155)

without the SDK it also complains about Array and map
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/a310e21f-cf0f-488f-85ef-f60d6b17dd64)

attempting to replace it with typedef or import alias only makes String value assign fail
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/0e6344c9-939e-4522-b906-fa0e93036536)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/8e08de03-1d5c-4637-b059-eb3601f545ba)

So i really dont know how to reproduce this one and  probably need  some more info or hints.

**Comment by Kyliathy** [comment]
public var someVar: String;

This works perfectly. And ctrl+clicking on String navigates me to the correct Haxe class: extern class String 

It's just the generics that are messed. And even that, it's just String. Everything else, such as Array<SomethingElse> works fine.
Navigating to Map for example works, leading to the correct Haxe class: typedef Map<K, V> = haxe.ds.Map<K, V>;

(so it goes without saying that the SDK is correctly set & indexed)

Do you have a debug log or can place some sort of debug flag so that I can give you more logs? :)

**Comment by m0rkeulv** [comment]
you could create a diagnostic zip file, if you dont want to send everything just open it and get the idea.log file
(i probably wont have the time to look at it the next 16-20 hours, but ill dig into it once i get an opportunity)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/7b7b236a-e2e1-41cf-85f2-ae9ce8f7b97a)

**Comment by Kyliathy** [comment]
I'm very grateful for your support! I will send the logs. Can you DM an e-mail via the Haxe Community?

Could I do something in order to make the String problem easier to spot in the logs? Are logs generated when the parser detects unknown types, such as those red underlines underneath String? Would perhaps opening/closing the file with problems generate such logs? 

Could I clean up the log somehow to make it easier for you? It currently sits at 2 MiB.

**Comment by m0rkeulv** [comment]
What version of the haxe toolkit are you using ?
also do you have Any classes, abstracts, enums etc that are called `Null` from the logs i see a lot of issues resolving the type from the SDKs abstract `Null<T>`

**Comment by m0rkeulv** [comment]
could you install  1.4.39 (https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.39) and create a small file that procedures the problem, and enable trace logging as the screenshots below show. then do some manipulation of the lines that are not working and then collect logs and diagnostics again

after you have done that remove the trace logging or it will probably slow down  the plugin quite a bit.
```
com.intellij.plugins.haxe:trace
```
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/0664adc4-d60e-4e45-a86d-0e33fba35ce5)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/f29452be-6489-49a8-aa82-4502fb1ca684)

**Comment by Kyliathy** [comment]
Hi! :). Having some urgent issues to handle these days. I'll get back soon with the necessary info! Also, I'm on Haxe 4.2.3, which I know is old but I somehow doubt this is the problem. I guess it's time for me to update after all these years :D

**Comment by m0rkeulv** [comment]
@Kyliathy do you still have this problem ?

**Comment by Kyliathy** [comment]
Yeap :(. But I discovered something very interesting just now.

I discovered a class where it DOES know about String and everything is fine. I'm e-mailing you the two classes since this is private code. But to summarize: in one class, I can't even navigate to String, it doesn't know it. And in another class IN THE SAME PROJECT/MODULE, it navigates successfully and I get no errors.

**Comment by m0rkeulv** [comment]
should be fixed in latest release
https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.4.46
