### ISSUE TITLE
Macro parameter parsing not working

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1160]
```haxe
@:build(MacroTest.Build({int: 123, bool: true, array: [true]}))

class MacroTest {
    public static function Build(data:Dynamic)
    {
        
    }
}
```
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/d3cde793-4445-40fd-aff6-78be21f9dc06)

As you can see in the image, it does not parse the macro parameters.

**Comment by m0rkeulv** [comment]
Fixed in 1.5.3
