### ISSUE TITLE
Resolving symbol fails on filter function.

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1165]
The generic variable is probably the cause of the problem.

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/c2913dec-64ba-4bc1-8580-322255870014)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/23dcd461-4462-489d-ae82-a53ced399379)

**Comment by m0rkeulv** [comment]
need to see `SampleObject` class to know whats wrong here.

**Comment by barisyild** [comment]
> need to see `SampleObject` class to know whats wrong here.

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/e922a10e-5ac5-40bb-b525-a1b75e391c00)

**Comment by m0rkeulv** [comment]
could you also past the code, so i dont have to type it for testing

**Comment by m0rkeulv** [comment]
if you need this to work right now,  just wrap the parameter in  parenthesis
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/b67a39d5-8ba7-4ad2-966a-6f20f40b28a9)
