### ISSUE TITLE
Wrong class constructor arguments counting

### ISSUE THREAD

**Issue by shaman4d** [HaxeFoundation/intellij-haxe#1167]
Class BO has 3 mandatory arguments in constructor. But when "complex" formula encounters IJ highlights it as wrong. More details in ss.
![Screenshot_1](https://github.com/HaxeFoundation/intellij-haxe/assets/483429/b69fe097-83d1-4434-8fad-f6041036d94c)

**Comment by m0rkeulv** [comment]
Do you have  multiple  classes named BO, or overloaded constructors ?
i cant seem to reproduce it, what version of the plugin  are you using ?
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/ae243b3b-f192-4f45-96e2-65dbfb406f4b)

**Comment by shaman4d** [comment]
I have base class BO, several subclasses. One of subclasses has constructor without parameters. I use latest version of the plugin.

**Comment by m0rkeulv** [comment]
could you share the constructor signatures in the different classes, or in anyway create an example that reproduces the problem that i can  look at. I am still unable to reproduce your problem. (this is my current attempt)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/6eefc6f1-fa42-408e-86c4-287a664a1e54)

**Comment by shaman4d** [comment]
I cannot reproduce it anymore even in work project. Sorry for bothering.

**Comment by m0rkeulv** [comment]
if that is the case it could have been caused by  some kind of caching that didn't invalidate correctly, those are a bit hard to track down but ill keep this case in the back of my mind whenever i work on caching stuff.
