### ISSUE TITLE
Intellij IDEA doesn't recognise basic types defined in StdTypes.hx

### ISSUE THREAD

**Issue by min-pascal** [HaxeFoundation/intellij-haxe#1169]
.. even though the std folder has been added as classpath they are still not recognised. not sure if this relates to the plugin or Intellij IDEA itself

**Comment by min-pascal** [comment]
same thing applies to Array and Int which reside in their own files. there is no complaints on String

**Comment by m0rkeulv** [comment]
Normally this would be automatically set up automatically when you add the SDK, but if you had to add it manually, make sure to add std paths both classpath and sourcepath.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/85cfabfd-1f8f-4014-b058-0e10d58b9803)

it might also help to force reload the project if it does not update  automatically. you can do this by right clicking in the project panel.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/a6c78818-d15a-4e25-99ee-d3469a51303c)

**Comment by min-pascal** [comment]
also adding the std folder to sourcepath fixed the issue

**Comment by min-pascal** [comment]
Have installed haxe with Homebrew on mac so path to haxe is different
