### ISSUE TITLE
Haxe plugin commands in the toolbar not syncing correctly across IntelliJ products

### ISSUE THREAD

**Issue by min-pascal** [HaxeFoundation/intellij-haxe#1171]
I use IntelliJ IDEA for haxe programming and Webstorm where the haxe plugin unfortunately is not available. When I put in a toolbar item of a haxe plugin command and the toolbar is synced it gets screwed in Webstorm and also in Intellij IDEA

**Comment by m0rkeulv** [comment]
the plugin has as far as i know never added any sync features,  best guess is that intellij tries to keep track of toobars without knowing that elements from the haxe plugin is unsupported in other IDEs.  any chance you could provide some  screenshots of how it looks in the different IDEs ?

**Comment by min-pascal** [comment]
That was also what I was thinking so I submitted a bug at jetbrains but it was considered a third party problem and I was sent here. I'll try to send some screens in the near future

**Comment by min-pascal** [comment]
The bug got reopened over at jetbrains .. the supporter on the other hand could see "tons of exceptions" coming from the plug-in when reading the logs
