### ISSUE TITLE
Feature request: Generate variables and methods

### ISSUE THREAD

**Issue by min-pascal** [HaxeFoundation/intellij-haxe#1173]
.. Like in the old Flash Builder days

**Comment by min-pascal** [comment]
Looking at closed issues this feature should already be there. I don't see any commands when running "Generate"

**Comment by m0rkeulv** [comment]
the feature is there for properties, but maybe you're looking for a getter/setter for normal variables ?
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/3d2f5696-6cd9-4b6c-930c-500a11fcee3d)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/5d61815e-d5d1-43f5-8cb3-29c3e34d8880)

**Comment by min-pascal** [comment]
I was hoping to be able to generate a member variable or function from an "Unresolved symbol"

**Comment by min-pascal** [comment]
.. being able to choose between member or local would also be nice

**Comment by m0rkeulv** [comment]
could you provide an example, i am not sure i understand the  "Unresolved symbol" part.
a before and after example would be helpful.

**Comment by min-pascal** [comment]
Something similar to the [QuickFixes](https://fdt.powerflasher.com/docs/Writing_Code_With_FDT#Class_.26_Interface_Generation) feature of FDT is what I am looking for

**Comment by m0rkeulv** [comment]
generate constructor, getters and setters should now work, i have also added  quickfixes for unresolved symbols so you can easly generate, local variables, fields, methods and functions.
