### ISSUE TITLE
IDE Exceptions

### ISSUE THREAD

**Issue by min-pascal** [HaxeFoundation/intellij-haxe#1176]
Once in a while Intellij IDEA is complaining about plugin related exceptions. From there you can bring up the "IDE Internal Errors" dialog where you can check out the stacktrace. The dialog also has a primary button with the label "Report and Clear All". Unfortunately nothing happens when this button is clicked so I guess the errors has to be reported manually. I myself have a hard time figuring out why these errors occur so I can't really give a clear description on how to reproduce them. My question is how would you like us to report these errors? Is it enough just to post stacktrace?

**Comment by m0rkeulv** [comment]
stacktraces and what version of the plugin and IDE your using is helpful.
I wont necessarily be able to reproduce and them fix them, but some of them i might if they are easy fixes like NullPointerExceptions etc..
