### ISSUE TITLE
Importing static variables feature is not implemented

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1180]
Intellij Idea:
![image](https://github.com/user-attachments/assets/a71aa965-1fc3-476d-a0bf-edb1faba105d)

[try.haxe.org](https://try.haxe.org/#0FFFe724):
```haxe
//use this for macros or other classes
class Macro {
	public static inline var TEST:Int = 1;
}
```
```haxe
import Macro.TEST;

class Test {
  static function main() {
    trace(TEST);
  }
}
```

**Comment by m0rkeulv** [comment]
import of static members works, but it looks like members starting with uppercase "confuse" the plugin, it cant tell if its a non-default named class  in a module or a member of a class. ill make a workaround for now that checks  both cases.
