### ISSUE TITLE
Latest release was not pushed to jetbrains marketplace

### ISSUE THREAD

**Issue by Dreaded-Gnu** [HaxeFoundation/intellij-haxe#1196]
Hello,
the latest release was not published to jetbrains marketplace. Is there something broken with upload or how is this working?

**Comment by m0rkeulv** [comment]
I have  uploaded it to Jetbrains marketplace now, it might  take a few days for them to approve it.

**Comment by m0rkeulv** [comment]
should be live  on jetbrains marketplace now

**Comment by Dreaded-Gnu** [comment]
thanks for pushing it to jetbrains marketplace
