### ISSUE TITLE
intellij community edition endlessly indexing

### ISSUE THREAD

**Issue by Dreaded-Gnu** [HaxeFoundation/intellij-haxe#1197]
Hello,
I noticed an issue that intellij community edition is endlessly indexing over and over again without finishing.

I'm using latest version of intellij community edition and latest release of HaxeToolkit plugin. Tested it with a trial of intellij ultimate and there the indexing is not endlessly indexing.

**Comment by m0rkeulv** [comment]
could you share what libs are in your project ? do you see any error reporting ?

**Comment by Dreaded-Gnu** [comment]
It is an openfl project and when I comment out all library dependencies / removing all `<haxelib name="..." />` it keeps indexing in an endless loop when opening the project.

What I discovered is when I change the project.xml it stops indexing, and the reload haxelib button appears which won't go away when I click on it.

Sadly there is no error message from plugin coming

**Comment by m0rkeulv** [comment]
I think i have fixed the issue. it seems like reloading the project  might have marked some files as changed causing to to want to reload again and again and again. i have made a new release that hopefully solves your problem.

https://github.com/HaxeFoundation/intellij-haxe/releases/tag/release-1.5.13

**Comment by Dreaded-Gnu** [comment]
Glad you found a fix. Will try it as soon as it is published to intellij market place and give some feedback than here. :)

**Comment by Dreaded-Gnu** [comment]
Strange thing is that it only affects intellij community edition. Do you have maybe an idea why it wasn't happening with intellij ultimate?

**Comment by Dreaded-Gnu** [comment]
Fix solved the issue with endless indexing within intellij community edition, thanks.
