### ISSUE TITLE
Parser fails to parse @:bitmap meta tag

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/intellij-haxe#124]
I tried to parse a file from flixel/FlxSprite.hx
https://github.com/HaxeFlixel/flixel/blob/master/flixel/FlxSprite.hx#L28

``` haxe
@:bitmap("assets/images/logo/default.png")
private class GraphicDefault extends BitmapData {}
```

"There is no default constructor available for openfl.display.BitmapData"

**Comment by EricBishton** [comment]
Tested in 0.11.2.  Cannot repro, so assumed fixed.
