### ISSUE TITLE
Parser issue: BlockStatement in call expression is not allowed

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/intellij-haxe#130]
Parser issue: BlockStatement in call expression is not allowed

``` haxe
trace({x;});  //parser attempts to parse it as object literal and fails
```

Instead it should be parsed as block statement I think... But this actually requires changes

TIR: STB-9358

**Comment by EricBishton** [comment]
Tested in 0.11.2.  Fixed.
