### ISSUE TITLE
If `extends` is empty, parser doesn't recover and doesn't shows classes below in completion

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/intellij-haxe#137]
If `extends` is empty, parser doesn't recover and doesn't shows classes below in completion

![Imgur](http://i.imgur.com/PmEtoqo.png)

``` haxe
@:test class Main extends  {
    public function new() {
        var a = new Sprite();
    }

    function test() {

    }
}

TIR: STB-9360
class SuperClass {

}
```

**Comment by as3boyan** [comment]
To reproduce it: 
Copy code, put caret to end of extends, trigger completion(Ctrl-Space)

Expected results:
Completion with `SuperClass` item.

Actual results:
Completion with no `SuperClass` item.

This issue is similar to one we had with `new` keyword, when it was empty - plugin was unable parse and show completion.

**Comment by EricBishton** [comment]
Will be in 0.11.2.
