### ISSUE TITLE
Tooltip is displaying an internal AST node name instead of a type.

### ISSUE THREAD

**Issue by boozook** [HaxeFoundation/intellij-haxe#198]
Ugly tooltip with text only for dev of Haxe-Idea-plugin.

For reproduce press ⌘ (or Ctrl) and roll mouse over any Type.

![screen shot 2015-04-04 at 0 59 56](https://cloud.githubusercontent.com/assets/888526/6989598/407489ea-da66-11e4-9c31-dcb5a17ca37c.png)

TIR: STB-9368

**Comment by fzzr-** [comment]
Works better in latest release.

**Comment by eliasku** [comment]
:+1: Have you check it in 0.9.9?
Now it reproduced just for cmd+alt+hover. But new issue must be created for in-place find usages `cmd+alt+hover` shortcut.

**Comment by EBatTiVo** [comment]
@eliasku - If you want a new issue for the 'in-place find usages' (or 'show implementations') version of this bug, go ahead and create it.  Then we can close this one.

**Comment by m0rkeulv** [comment]
Fixed in dev, will be part of next release
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/7803bc08-352b-4137-a9d3-fbf3bba9ab3b)
