### ISSUE TITLE
Child class of Parent with Type parameters, has no auto-complete.

### ISSUE THREAD

**Issue by grisevg** [HaxeFoundation/intellij-haxe#24]
For example:

``` haxe
class StringChild extends Parent<String> {}
class Parent<T> {}
```

Auto-complete won't work for `StringChild`, there won't be a way to navigate to it's members, refactor or even see it highlighted as a member.

Another very good and important example is the popular `HaxeFlixel` project - any class that extends `FlxGroup` (https://github.com/HaxeFlixel/flixel/blob/master/flixel/group/FlxGroup.hx) won't have auto-complete or any other features working for them.

TIR: STB-7288

**Comment by EricBishton** [comment]
Fixed in 0.11.0-RC3.  Probably by https://github.com/HaxeFoundation/intellij-haxe/commit/f128e86bf0fa88a8b6d8dfd66e2fa63531c9a18a
