### ISSUE TITLE
parser error: expect `;` after field declaration with object literal

### ISSUE THREAD

**Issue by giabao** [HaxeFoundation/intellij-haxe#282]
![err1](https://cloud.githubusercontent.com/assets/1702709/7882071/16bec4ae-0634-11e5-852d-4e09e65468cb.png)

**Comment by giabao** [comment]
Paser error: expect object literal when init local var or class field (instance or static) with `{ }`
![err2](https://cloud.githubusercontent.com/assets/1702709/7882178/248e58a0-0635-11e5-9a28-0402b29de20f.png)
![err3](https://cloud.githubusercontent.com/assets/1702709/7882189/485de1ec-0635-11e5-9a19-dcc35b0e33dc.png)

**Comment by EBatTiVo** [comment]
@giabao A few details, please.  Plugin version? Is this with your own build? IDEA version?  

Did this use to work and just broke yesterday when I checked in the fix for #278?

**Comment by giabao** [comment]
Sorry :cry: 
IDEA 14.1.4 (IU-141.1192)
plugin: build from 0ac04b6c8daadd5961de0d6a77ba5a9061bb2a0c (Merge pull request #280 from TiVo/FixIssue278ReturnAnObjectLiteral )

I've just try plugin [0.9.4 for IDEA 14.1.3](https://plugins.jetbrains.com/update/index?pr=idea&updateId=19942) and my own build from fd9c9d57867119b2a061825b900bb2a7388417ab - same error.

**Comment by as3boyan** [comment]
I think semicolon is mandatory after brackers (We didn't solved this issue yet)

**Comment by as3boyan** [comment]
BTW if we solve this, new test cases for this should be added

**Comment by eliasku** [comment]
+1 subscribe.

Adding text-format repro:
```
class Test {
    static var bug = {
        name:"Hello"
    }
    
    static function main() {
        trace(bug.name);
    }
}
```
This code is compiled OK

**Comment by EricBishton** [comment]
Tested in 0.11.2:  Works correctly now.
```haxe
package ;
class TestIssue282 {
    static function main() {
        var foo = {} //OK
        var baz = 1;
    }
    var foo = {} //bug
    var baz = 1;
    static var foo2 = {x: 1} //bug - similar previous
    var baz2 = 1;

    static function main2() {
        var foo = { 1; } // <-- Error was before '1', "'}' expected, got '1'"
    }
    var foo3 = { 1; } // <-- Error was before '1', "'}' expected, got '1'"
}
```
