### ISSUE TITLE
String interpolation should be just detected for single quoted strings

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/intellij-haxe#289]
Single-quoted strings have string interpolation

```
test=1
'Hello$test'
```

It would output Hello1

```
test=1
"Hello$test"
```

Would output Hellotest. But ide it is providing autocompletion for both single and double quotes and should just provide for single quotes.

**Comment by romanmikhailov** [comment]
Also need remove incorrect highlighting of string constants with $ symbol.

![image](https://cloud.githubusercontent.com/assets/1431183/8257736/8905bbbe-16b8-11e5-92e8-8bf859c789bf.png)

**Comment by EricBishton** [comment]
Fixed with PR #1055.  Will be released in plugin version 1.4.
