### ISSUE TITLE
When typing `${` adds extra closing brace `}`

### ISSUE THREAD

**Issue by boozook** [HaxeFoundation/intellij-haxe#298]
Plugin v: «0.9.4 for IDEA 14.1.3»
Idea v: Community Edition 14.1.3 (141.1010)
JRE v: 1.8.0_40-b27 x86_64

Steps for reproduce:
In the any function body or any block type symbols:
1. `$`
2. `{`
Result: `${}}`.
But needed: `${}`.

![braces mov opt](https://cloud.githubusercontent.com/assets/888526/8026143/3042bbe6-0d74-11e5-9b6e-933bf400d1b8.gif)

**It happening only if it outside string**.
E.g. `"${"`->`"${}"` and `'${'`->`'${}'` - works fine.

**Comment by EBatTiVo** [comment]
Verified.
