### ISSUE TITLE
Resolving types having parameters (generics) does not work for chained types.

### ISSUE THREAD

**Issue by EBatTiVo** [HaxeFoundation/intellij-haxe#318]
When we have one generic type resolving to another, things work well.  When a second (or more) level is added, resolving is incomplete.  

A sample of code can be found in https://github.com/TiVo/intellij-haxe/blob/master/testData/paramInfo/ParamInfo7.hx.  The test is currently disabled; it does not pass.

The crux of the problem is the need to have all typing info before resolving, but needing to resolve to get the typing.  The portions of the resolver dealing with specialization (particularly HaxeResolveUtil.specializeByType()) need to be rewritten.  The recursive nature of the entire resolving subsystem is part of the problem and makes debugging extremely difficult.

**Comment by EricBishton** [comment]
Fixed in 0.11.0-RC3.  https://github.com/HaxeFoundation/intellij-haxe/commit/f128e86bf0fa88a8b6d8dfd66e2fa63531c9a18a
