### ISSUE TITLE
Object declaration parsing error

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/intellij-haxe#365]
I can use string like field names in haxe object declaration.
Example:
var obj = {"stringfield": "Hello!"};

Parser breaks with message: '{' unexpected

String field needed for field with names equivalent to haxe keywords:
var incorrectObj = {var: "g"};
var correctObj = {"var": "g"};

Environment:
OS: Windows 7 32 bit
IDEA 14.1.5
Haxe plugin 0.9.6
java version "1.5.0_07"

**Comment by EBatTiVo** [comment]
This is a parser (BNF) issue.

So, the workaround here is not to use keywords as field names, correct?

**Comment by codeservice** [comment]
Works as workaround.
Problem if developer need object with keyword like field name.

**Comment by EBatTiVo** [comment]
I agree that there is a problem, though I think that is unlikely that a developer *needs* to use such a named field in most scenarios.

**Comment by codeservice** [comment]
Yes, not frequent case.

Examples:
var person = {name: "John", has: {package: 234234, import: "from china"}};
I can't compile this on haxe, need to wrap in "package" or replace with different name

Different kind of parsers written on haxe may need objects with keywords. Hard to replace, need "" wrap

**Comment by EricBishton** [comment]
Fixed with #702:  https://github.com/HaxeFoundation/intellij-haxe/commit/4343875652ec30114dadfb07d16d91b86a457bd2
