### ISSUE TITLE
[std] @:require parsing broken

### ISSUE THREAD

**Issue by eliasku** [HaxeFoundation/intellij-haxe#418]
Parsing of `@:require(haxe_ver >= 3.1)` is broken.
![image](https://cloud.githubusercontent.com/assets/3038174/13070698/775512d4-d49f-11e5-9abb-9aff89ff8526.png)
For example that affects `haxe.macro.Context` class, and some methods are unresolved and missed for completion.

Repro:

```
class Test {
    @:require(haxe_ver >= 3.1)
    function test() {}
}
```

Version: 0.9.9, IDEA 15, OSX

**Comment by EBatTiVo** [comment]
Seems like the '>' sign isn't being allowed.  That error message comes from the parser.
