### ISSUE TITLE
[Regression] Intellij 13.x plug-in path's are broken causing 404.

### ISSUE THREAD

**Issue by haysclark** [HaxeFoundation/intellij-haxe#468]
Intellij 13.x user can not longer download the older version of the plug-in because of broken paths.

**Repro:**
1. Open Intellij 13.x
2. Open plug-ins
3. Search for Haxe plug-in, version 8.1 shows up.
4. Click install.

**Result:**
<img width="605" alt="screen shot 2016-05-22 at 11 54 55 am" src="https://cloud.githubusercontent.com/assets/138324/15456733/857cf798-202e-11e6-8ba1-5b23251b6097.png">

**Expected:**
Version 8.1 should install.

**Comment by EBatTiVo** [comment]
In fact, the broken link is at JetBrains' plugin repository over which we (the current team intellij-haxe team) have no control. 

That said, IDEA 13.1.x should offer version 0.9.6, which is the last available version that supports 13.1.x platforms.  However, the latest patch release of the 13.1 code line has brought us to a number beyond the installation cutoff for the plugin.  It should still be possible to create a build that will allow 0.9.6 to be installed on any IDEA built from the 135 code line.  It simply means downloading the code from the 0.9.6 release and changing the "plugin.installable.until" property to 135.* inside of the idea_v13.1.properties file.

**Comment by EricBishton** [comment]
2013.x hasn't been supported for a while now, and nobody in the community has wanted to fix this, so... closing.
