### ISSUE TITLE
Compile with hxml cause unnecessary dependencies to be added

### ISSUE THREAD

**Issue by flajeu** [HaxeFoundation/intellij-haxe#477]
When setting the Compile with HXML, unnecessary dependencies get added to the project dependencies.

Version: 0.9.10 for IDEA 15 
Step to recreate : 
1 - create a hxml file  : 

-main igt.core.gleclient.GLEClient
-cp ../src
--macro include('igt.core.gleclient')
-js ../outgleclient.js

2 - set the Compile with to HXML and set the hxml file to point to this file ( click apply )
3- close project and reopen ( some time need to reopen twice.. ) 
4 - look at the module setting dependencies 
new dependencies are added  - haxlib|../scr 

this does not cause any error but is a nuisance... 
not sure why these need to be added to the project .iml..

**Comment by EBatTiVo** [comment]
When your project starts up, the Haxe plugin scans your sources and tries to determine if all of the required libraries are part of the project.  If not, it adds them (with the "haxelib|" prefix).  It's trying to fix your project for you.

That said, there are a number of issues filed against the auto-library-locating mechanism, and we need to revisit it.

**Comment by EricBishton** [comment]
Fixed a while ago now.  Closing.
