### ISSUE TITLE
Completion is afraid of EitherType with functions

### ISSUE THREAD

**Issue by winmain** [HaxeFoundation/intellij-haxe#512]
Completion don't work properly for function with `EitherType` of two functions.

``` haxe
import haxe.extern.EitherType;
import js.html.MouseEvent;

class Test {
  public function some(handler: EitherType<MouseEvent -> Void, Void -> Void>): Void {}

  public function test() {
    som| // <- no completion here
  }
}
```

If I change `handler` type to simpler construction like `EitherType<String, Int>` everything starts to work fine.

Plugin version: `0.10.1-RC2`
Idea: `2016.2`

**Comment by EBatTiVo** [comment]
Needs a BNF update to allow function types as Generic parameters.

**Comment by bynuff** [comment]
I'm working on it now. Hope it will be fixed soon.

**Comment by EricBishton** [comment]
Fixed.  With #616?

**Comment by winmain** [comment]
Approve. Works correctly with the latest build.
