### ISSUE TITLE
Feature request: Collapsible regions in editor

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/intellij-haxe#529]
The request is to support regions, similar to ActionScript

```haxe
//region MyCodeRegion
var a = 100;
var b = 200;
//endregion
```

---

Flowplay is interested in paying to support the development of this and other issues:

https://github.com/TiVo/intellij-haxe/issues/528
https://github.com/TiVo/intellij-haxe/issues/530
https://github.com/TiVo/intellij-haxe/issues/531

Thanks everyone :smile:

**Comment by EricBishton** [comment]
Implemented in #744.
