### ISSUE TITLE
Version 0.10.1 is not available for installation on IDEA 2016.3.2.

### ISSUE THREAD

**Issue by EBatTiVo** [HaxeFoundation/intellij-haxe#540]
Version 0.10.1 installs correctly with IDEA 2016.3.1, but does not install with 2016.3.2.

The build number for 2016.3.2 is larger than 9999, which is the maximum build number that is allowed for 2016-targeted builds.  Thus, 2016.3.2 users are being asked to downgrade to 0.9.7.  @SlavaRa has created pull request #539 to fix this (and expand the number of tested builds for .travis).

Reported by @demurgos

**Comment by EricBishton** [comment]
Release 0.10.1.1 addresses this.

**Comment by demurgos** [comment]
I confirm that it works fine (I just received a notification in my IDE).
