### ISSUE TITLE
Windows build of the plugin doesn't work without manual intervention.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#558]
The Windows build of the plugin doesn't compile correctly unless the Grammar-Kit plugin is downloaded and expanded by hand.  There may be other issues with PSI generation as well: @as3boyan was missing classes when compiling.

The first problem is that Gramar-kit is downloaded via a 'wget' command.  That doesn't exist in the normal Windows distribution.  Downloads need to be dealt with by ant, not a bash script.

**Comment by m0rkeulv** [comment]
i have written a set of Ant tasks to solve this and made a pull  request #668 ,
let me know if it solves this issue and/or if i should change  anything.

**Comment by EricBishton** [comment]
Yep.  This has been long fixed...
