### ISSUE TITLE
alt+enter does not create a new method

### ISSUE THREAD

**Issue by b005t3r** [HaxeFoundation/intellij-haxe#571]
When I try to create a new method by simply putting in its name somewhere in the code, like so:
```haxe
newMethod();
```
and I hit alt+enter, there's no option to create a new method.

IDEA 14.0
plugin 0.10.1.TestCompilerCompletion
haxe 3.4.0
haxelib 3.3.0

**Comment by roipeker** [comment]
+1 on this one... Intellij Inspections support non existent.

generate: methods, parameters, variables with different scopes, class, interfase, constructor... is muscle memory for several Intellij users.

**Comment by m0rkeulv** [comment]
fixed
![image](https://github.com/user-attachments/assets/9b829647-15a1-4452-b833-596d7ee9bbb8)
