### ISSUE TITLE
Haxe support plugin for IDEA doesn't support version 2017.

### ISSUE THREAD

**Issue by VinceHuiWan** [HaxeFoundation/intellij-haxe#581]
Today after I updated the IDEA to the version 2017.1, I cannot use Haxe Support plugin now.

**Comment by EricBishton** [comment]
Ah, IDEA 2017.1 is out.  I knew it was coming real soon now.  I'll get to this shortly.

**Comment by VinceHuiWan** [comment]
I there any way to roll back the version of IDEA to 2016.1? because I need to write some code these day?

**Comment by EricBishton** [comment]
@VinceHuiWan - Yes! There is.  Download IDEA 2016.1 here: 
http://download-cf.jetbrains.com/idea/ideaIU-2016.1.4.tar.gz (for linux).
http://download-cf.jetbrains.com/idea/ideaIU-2016.1.4.exe (for windows).
Multiple versions of IDEA can be installed simultaneously, though they sometimes use different configuration directories -- named for the major version (e.g. ~/.IntelliJIdea2016)

**Comment by VinceHuiWan** [comment]
Thank you

**Comment by SlavaRa** [comment]
I will try to do PR at the weekend, I need to test the plugin a bit

**Comment by EricBishton** [comment]
PR #599

**Comment by EricBishton** [comment]
@SlavaRa - I already had it in-process and I didn't want you to have to duplicate the work.  A code review would be appreciated, though.  :-)

**Comment by SlavaRa** [comment]
@EricBishton okay:)

**Comment by EricBishton** [comment]
OK.  The last of the changes are checked in.  (It actually took some effort to get the tests to pass.)  ea84891877365662ba1d7c7740381d86bfd9da5a
It will be in the 0.11.0 release, coming this week.

**Comment by vartagg** [comment]
Having problems with release? Very much waiting for your plugin for 2017

**Comment by EricBishton** [comment]
Working on it as we speak.  I've already written the change notes, etc.  I'm smoke testing right now.

**Comment by EricBishton** [comment]
0.11.0 is released and supports IDEA 2017.1.
