### ISSUE TITLE
Optimize imports too slow

### ISSUE THREAD

**Issue by kodekuru** [HaxeFoundation/intellij-haxe#631]
Optimize imports too slow afer commit '8c97aedbad0696d48d27481c3a604379fc4fa749'. It becomes faster again when 'Log.trace' calls are remarked.

**Comment by EricBishton** [comment]
That's interesting.  I'll see what I can do about getting less overhead out of LOG.trace().

**Comment by EricBishton** [comment]
Fixed.  PR #636.  
@kodekuru Thanks for reporting this!

**Comment by EricBishton** [comment]
PR was pulled.
