### ISSUE TITLE
HaxeTypeResolver don't condiser specialization

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#632]
All methods of resolver do not pay respect to specialization of classes that contains methods/fields/parameters/etc, because of that a lot stuff (e.g. completion lookup) recognizing types as plain T/K/V/etc.

**Comment by EricBishton** [comment]
@mayakwd Let's be a bit more specific about this one:  
Presuming that you're working with your own build, Ilya, what is the latest commit that you have on your branch when you see this?  
Can you give an example of code that is parsing and resolving incorrectly?

Version 0.11.0-RC3 definitely has the code which fixes this.  There are still two open issues with it: #615 (Incorrect resolution order for local variables and type parameters; and #635 Incomplete resolution of parameterized types (generics) when type parameters are themselves parameterized types.

**Comment by mayakwd** [comment]
May be I'm just not understood cases/purposes of using HaxeTypeResolver.
Example code:
```
class Node<T> {
    public var required(default, null):Bool;
    public var value(default, null):T;
    public function new(required:Bool, ?value:T) {
        this.value = value;
    }
}
```
I'm trying to get type of the parameter "value", using ```HaxeTypeResolver.getTypeByTypeTag```:

```
final HaxeParameterModel model = new HaxeParameterModel(parameter);
final HaxeTypeTag typeTag = model.getTypeTagPsi();
ResultHolder resultHolder = HaxeTypeResolver.getTypeFromTypeTag(typeTag, parameter);
```

Type will be recognized as just `T`, and all of that because there is no place to place specialization in any method of HaxeTypeResolver.

After getting a type: https://github.com/HaxeFoundation/intellij-haxe/blob/master/src/common/com/intellij/plugins/haxe/model/type/HaxeTypeResolver.java#L151 , method ```HaxeTypeResolver.getTypeFromTypeOrAnonymous``` not checking any specialization and returning just 'T': 
https://github.com/HaxeFoundation/intellij-haxe/blob/master/src/common/com/intellij/plugins/haxe/model/type/HaxeTypeResolver.java#L200-L207

**Comment by mayakwd** [comment]
I did not dig it deeply, but guess same thing is touching HaxeLookupElement:

![Rendered list of available fields and methods](http://g.recordit.co/4m6kOxw879.gif)

```
class TestClass {
    public static function main() {
        var node = new Node<String>(false, "");
        node.| // <- cmd/ctrl+space
    }
}

class Node<T> {
    public var required(default, null):Bool;
    public var value(default, null):T;
    public function new(required:Bool, ?value:T) {
        this.value = value;
    }
}
```

**Comment by EricBishton** [comment]
To get the proper value, you need to resolve Node<T> using the instantiation reference (the place where a variable is declared giving the parameter type to substitute for T).  Otherwise, there is nothing telling us what a 'T' is.

To use your example, first we have to figure out that the left-hand reference is `node`.  Then, we have to resolve `node` to get its declaration -- as a HaxeResolveResult.  That gives us the specialization that we need (which will eventually be sent on to the HaxeResolveResult.create) when we resolve each of the methods to get the completion list.  

It will take me a bit to get this written out in code.  I can go off and do it for the completion list, and that will let me prove to myself that I've got it right, and you'll have an example to work off of.

**Comment by mayakwd** [comment]
My pull-request already brings getting specialization from ```new Expression<Type>```, but i haven't found any way to apply during resolving of method's parameter

**Comment by EricBishton** [comment]
That happens during HaxeClassResolveResult.create(class, specialization).  The specialization that is passed in is matched up with the type parameters from the resolved class in specializeByParameters().

**Comment by mayakwd** [comment]
`HaxeGenericSpecialization.get` returning HaxeClassResolveResult, but I need to get SpecificHaxeClassReference, and I'm still looking for the solution.

**Comment by EricBishton** [comment]
HaxeClassResult.gethaxeClass() gives you the resolved class.  A SpecificHaxeClassReference is part of the models -- which is Soywiz' code -- so you're not going to get one of those out of anything that expects to manipulate the PSI.  You'll have to construct one using one of its myriad withXXXX() methods.

**Comment by mayakwd** [comment]
Yep, I thought about it, but haven't found simple way to do this, it's not that simple to create specifics (ResultHolder), from HaxeClassResolveResult.

And I'm not sure that I'm in right way. Classes that inherits from generic-based classes like:
```
class StringNode extends Node<String> {
...
```

Are giving right result with ```HaxeTypeResolver.getTypeFromTypeTag```
But I can't properly resolve methods parameters for "new Node<String>()" 
It's still giving me "T" instead of Type, I missed something, but can't realize what exactly
