### ISSUE TITLE
Lexer support of conditional statement with single-quotes

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#638]
Right now HaxeLexer can't parse code like:

```
#if (haxe_ver < '3.3')
...
#end
```
it's terminating with message: 
```
[HaxeConditionalCompilationLexerSupport.conditionEnd]  - Ending condition before it is complete: ' (haxe_ver < '
```

but it's a valid expression for compiler.

**Comment by EricBishton** [comment]
Hmm.  I must not have handled single-quoted strings properly.  Should be an easy fix.

**Comment by mayakwd** [comment]
Well done
