### ISSUE TITLE
Not working in PyCharm 2017.1

### ISSUE THREAD

**Issue by vartagg** [HaxeFoundation/intellij-haxe#642]
After enabling this plugin and opening existing haxe project, there is no possibility to open .hx files. These files just not opened after double-click on it. Also there are several errors in IDE's logs, I submitted the reports into JetBrains bugtracker

**Comment by EricBishton** [comment]
Unfortunately, I didn't find your reports on JB's bug tracker.  Can you please provide links, or repost them as issues here?

That said, I can say that the Haxe plugin relies heavily on the Java language implementations in IDEA.  That is, we use classes outside of the openapi and depend upon them being available in the application run-time.  However, JB regularly strips those classes from some of their products (such as AppCode).  The JB plugin repository is _supposed_ to look at the classes required by the plugin and only allow downloading the plugin to the environments that provide all of the used classes.  It's my experience that they don't do such a good job...

At any rate, can you tell me if the reported error is new behavior?  With which version of the plugin and PyCharm did it last work, and which versions are you using now?  Which platform (e.g. Linux, OSx, etc.) are you using?

**Comment by EricBishton** [comment]
Issue #643 is a duplicate and shows that there are classes that exist in IDEA, but are stripped from the PyCharm release jars (by JetBrains).  You might get PyCharm to work by adding the IDEA lib/idea.jar or lib/openapi.jar to your classpath.  If you try, you should use jars from the version of IDEA (CE or Ultimate) that most closely matches the version of PyCharm that you are using.  YMMV.

I may just have to mark the plugin as non-compatible. :-/

**Comment by vartagg** [comment]
>Unfortunately, I didn't find your reports on JB's bug tracker. Can you please provide links, or repost them as issues here?
Sorry, I haven't. I though that JetBrains providing details about crashes to plugin developers, but it seems that no. My reports were from IDE. 

>Issue #643 is a duplicate and shows that there are classes that exist in IDEA, but are stripped from the PyCharm release jars (by JetBrains).
Thanks for the explanation, didn't know about this circumstance. I'll try a method you talked about

**Comment by EricBishton** [comment]
Let me know how it goes.  If you find a solution, I'll put it up in a FAQ.

**Comment by vartagg** [comment]
The main reason I tried Haxe plugin with PyCharm was a purchased license for this IDE. It turns out that there is a free IDEA Community edition, so I no longer need in PyCharm as IDE for Haxe. At now I'm using IDEA with this Haxe plugin and everything is ok about its working. Thank you.
