### ISSUE TITLE
Support for import.hx

### ISSUE THREAD

**Issue by Matan** [HaxeFoundation/intellij-haxe#647]
Currently version 0.11.0 doesn't support the `import.hx` feature: https://haxe.org/blog/importhx-intro/ .

Adding support for this feature would be greatly appreciated.

**Comment by EricBishton** [comment]
The good news is that @mayakwd is currently working on it, along with the long-overdue integration of Soywiz' semantic annotation and resolver updates.

**Comment by nadako** [comment]
Any updates on this? This is one of the important ones for us.

**Comment by EricBishton** [comment]
Add in PR #1042.  Will be in 1.4 release.
