### ISSUE TITLE
Runner of "Haxe Application" is not working in Intellij IDEA 14

### ISSUE THREAD

**Issue by suhinini** [HaxeFoundation/intellij-haxe#66]
It does trigger making of module but actual Neko is not executed. Tried specifying "Alternative executable" but still nothing.

TIR: STB-7300

**Comment by EBatTiVo** [comment]
Now that we're supporting Idea version 14, this should be marked as a bug.

@as3boyan fixed some code for v14 HaxeRunner.java in this commit: 470f7420fb88bc5a993656dde66025d133a1d505

This is likely fixed, but I wasn't able to test it quickly.  Has anybody else tried it in 0.9.3?

**Comment by sganapavarapu1** [comment]
I'm able to launch my application in 14.1.1 build 141.178
(openfl with lime toolchain for cpp target on linux centos 6.5)

I'm able to debug them as well.

**Comment by mayakwd** [comment]
No relevant anymore
