### ISSUE TITLE
MongoDB query error

### ISSUE THREAD

**Issue by varadig** [HaxeFoundation/intellij-haxe#662]
When I wanted to create query like this:

`var condition:Dynamic = {"_id" : update.foundationID,"events" : {"$elemMatch":update.eventID}};
`

but the editos say to me:
![screen shot 2017-08-30 at 13 09 35](https://user-images.githubusercontent.com/6317148/29869731-7e731918-8d84-11e7-871c-3d29758c553b.png)

If I use in this way, the editor dont show me error:
```
var condition:Dynamic = {_id : update.foundationID, events : {}};
Reflect.setField(condition.events, "$elemMatch", {_id:update.eventID});

```
But in this way, I cant create complex query with operators

If I compile with haxe in cli, everything is oke.

**Comment by EricBishton** [comment]
@varadig  Are there follow-on errors (e.g. the rest of the file is unrecognized), or is the issue localized to that statement?

**Comment by varadig** [comment]
@EricBishton after this statement, rest of the file is unrecognized. Tomorrow I will include screenshoot with more detail.

**Comment by varadig** [comment]
![screen shot 2017-08-31 at 12 01 47](https://user-images.githubusercontent.com/6317148/29918217-ee5a3700-8e44-11e7-964d-a77c83c15183.png)

**Comment by varadig** [comment]
Any update for this issue?

**Comment by mayakwd** [comment]
Not yet, looking for workaround

**Comment by EricBishton** [comment]
@mayakwd  I think that
```bnf
objectLiteralElement ::= (identifier | OPEN_QUOTE REGULAR_STRING_PART CLOSING_QUOTE) ':' expression {recoverWhile="object_literal_part_recover"}
```
should become
```bnf
objectLiteralElement ::= (identifier | OPEN_QUOTE REGULAR_STRING_PART CLOSING_QUOTE) ':' (expression | objectLiteral) {recoverWhile="object_literal_part_recover"}
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mayakwd** [comment]
@EricBishton tried that already, won't help :-(

**Comment by EricBishton** [comment]
According to @mayakwd, the problem is (also??) with the identifier portion.  So, perhaps:
```bnf
objectLiteralElement ::= (identifier | stringLiteralExpression) ':' (expression | objectLiteral) {recoverWhile="object_literal_part_recover"}
                                       ^^^^^^^^^^^^^^^^^^^^^^^       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by varadig** [comment]
theres no hope to fix this issue? I realy need to use complex query but I cant with IntelliJ.

**Comment by mayakwd** [comment]
@varadig. i'll dig into it tomorrow

**Comment by varadig** [comment]
@mayakwd, thank you very much!

**Comment by EricBishton** [comment]
I've fixed it on my personal work repo.  I'll make a PR once it builds and tests cleanly.

**Comment by varadig** [comment]
I will test asap! Thanks!!!
