### ISSUE TITLE
Error:No main class for module: untitled Ubuntu 16.04

### ISSUE THREAD

**Issue by cancandan** [HaxeFoundation/intellij-haxe#663]
Installed haxe following https://haxe.org/download/linux/
Installed Haxe Plugin withing intellij
Version: 0.11.1 for IDEA 2016.1 through 2017.x

After creating a project and a Main class I get this error when trying to build

package ;
class Main {
    public function new() {
    }
}

**Comment by EricBishton** [comment]
Getting an error is correct.  

This is the error you should have been getting: `Main.hx:2: lines 2-5 : Invalid -main : Main does not have static function main.`

Can you post a screen shot of your Module and SDK settings?  (Or zip up your .iml and .ipr files -- or .iml and .idea directory -- and post them?)

**Comment by cancandan** [comment]
![image](https://user-images.githubusercontent.com/1025807/30055095-0b275b92-9237-11e7-8f7d-83f3407d3521.png)

![image](https://user-images.githubusercontent.com/1025807/30055148-2caf1c82-9237-11e7-982a-632c93249e31.png)

![image](https://user-images.githubusercontent.com/1025807/30055156-35c48596-9237-11e7-88a3-1402a7df1564.png)

![image](https://user-images.githubusercontent.com/1025807/30055237-7aa96f32-9237-11e7-9ce8-aab81098cd02.png)

**Comment by EricBishton** [comment]
How are you building your module?  If you are using the "Haxe Compiler" as in the following screen, then you must have the main class specified:

![image](https://user-images.githubusercontent.com/12093217/30073714-b932188a-9223-11e7-8d81-bea1e4a9b186.png)

If you are using NMML or HXML, then the main class must be specified in the project.nmml/.hxml file.

**Comment by EricBishton** [comment]
If that doesn't fix it, can you please post the screen shot of the above screen from your project?

**Comment by cancandan** [comment]
Thank you, that fixes it.
