### ISSUE TITLE
Haxe 4: Parse 'case var' syntax change

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#669]
'var' is now allowed between case and variable name to differentiate short capture variables in switch blocks.

See github.com/HaxeFoundation/haxe/issues/6207.

Also consider adding checks for this to semantic analysis.

**Comment by Simn** [comment]
Note: This was partially allowed in Haxe 3 as well. It was supposed to work in all patterns, but didn't correctly parse at toplevel-patterns. However, this should have worked in Haxe 3: `case Some(var x):`

**Comment by EricBishton** [comment]
Thanks, Simon.  I didn't check to see if the functionality was already there.  I just wanted to get a reminder in place, given that there's been action on it.

**Comment by m0rkeulv** [comment]
to me it looks like everything parses fine here so ill close this one
![image](https://github.com/user-attachments/assets/8f07f64e-c3ce-4c65-8f31-3aa61e00fec8)
