### ISSUE TITLE
Add keyword 'final' for Haxe 4 compatibility.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#670]
'final' is now allowed before method names.
It is also now allowed _instead_ of 'var' for a variable declaration, including structure declarations.

See https://github.com/HaxeFoundation/haxe/issues/6596 for details.

Also consider adding final processing to semantic analysis.

**Comment by nadako** [comment]
That's one of the things breaking completion for types that have `final` in it, would be nice to have it fixed.

**Comment by EricBishton** [comment]
Fixed by #804.  Will be in the 1.1 release.
