### ISSUE TITLE
Add new function type syntax for Haxe 4.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#677]
https://github.com/HaxeFoundation/haxe/pull/6645#issuecomment-334896589, which implements HaxeFoundation/haxe-evolution#23

**Comment by EricBishton** [comment]
See also https://github.com/HaxeFoundation/haxe/pull/6667

**Comment by nadako** [comment]
Yes please! :)

**Comment by EricBishton** [comment]
@mayakwd  Since #777 was merged, can we close this?  It will be released in 1.1.0

**Comment by mayakwd** [comment]
Yep.
