### ISSUE TITLE
hxml.bnf link is broken in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shawwn** [HaxeFoundation/intellij-haxe#689]

**Comment by EricBishton** [comment]
Thanks!

**Comment by shawwn** [comment]
Sure. Could I join your Slack channel? I'm very interested in Haxe + IDEA tooling.

**Comment by shawwn** [comment]
Alternatively, does the project have a Gitter chatroom? Everyone seems to use that as faux IRC nowadays.

**Comment by EricBishton** [comment]
You can certainly join haxe.slack.com.  There is an intellij-haxe channel there.  There's not much activity, but more people joining can only help that.  You can request access at:  http://hxbot-slack.herokuapp.com/invite/form.

There is also a slack channel for the plugin's financial contributors.  I always monitor it, and our regular devs are on it as well.  It doesn't have a lot of traffic, but it gets my priority attention.  Check out https://www.patreon.com/EricBishton if you'd like to know more about that.
