### ISSUE TITLE
Error when default: case is on the top of a switch

### ISSUE THREAD

**Issue by Kendja** [HaxeFoundation/intellij-haxe#697]
EXAMPLE
```HAXE
    public function setVersion(param1 : Int) : Void
    {
        switch (param1)
        {
            default:
                this.setColor(0);
            case 1:
                this.setColor(1);
            case 2:
                this.setColor(2);
        }
    }
```

![image](https://user-images.githubusercontent.com/1694998/32766493-fe33e334-c930-11e7-8a05-6a25016cfc10.png)

_Version: 0.11.1 for IDEA 2016.1 through 2017.x_

**Comment by m0rkeulv** [comment]
as far as i can tell this is no longer a problem, its also related to quite old versions of the plugin so i think this has been fixed at some point but the issue was forgotten open.
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/8752d76b-a2c3-433b-898c-ae251881b152)
