### ISSUE TITLE
Remove completion for fields marked with @:noCompletion

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#729]
Check https://github.com/HaxeFoundation/intellij-haxe/pull/694#discussion_r157932388

**Comment by EricBishton** [comment]
When we get around to this, I'd like to think about adding a checkbox -- or maybe a library attribute? -- so that folks who are developing the library can continue to get proper completions.

**Comment by mayakwd** [comment]
I think it should be added as a checkbox for module\project settings.

**Comment by m0rkeulv** [comment]
while there's no settings/checkbox for this feature, it is implemented so i am closing this one.
![image](https://github.com/user-attachments/assets/b0aedc7a-d543-42b1-b396-440678116b9f)
