### ISSUE TITLE
Class name could be null for anonymous types

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#732]
https://github.com/HaxeFoundation/intellij-haxe/pull/694#discussion_r158422831

**Comment by mayakwd** [comment]
@EricBishton, could you please tell me when we are using `HaxeReferenceImpl.toString` method actually? And why... Can't find any usage (through breakpoint).

**Comment by EricBishton** [comment]
Right.  It's probably implicit in most places (e.g. through something like `LOG("Reference: " + ref);`).  I know that it's used in tests, but that's what the 'if' is there for.

It may also be in (currently) disabled logs -- most likely in the resolver.

**Comment by EricBishton** [comment]
Also, toString() is used by the debugger to display the current value of an instance.  That is most likely where I needed it in the first place.

**Comment by mayakwd** [comment]
Okay, that's reasonable
