### ISSUE TITLE
Intellij IDEA 13.1 freezes when debugging with breakpoints set

### ISSUE THREAD

**Issue by ihamer** [HaxeFoundation/intellij-haxe#77]
I am using the debugger from TiVo/debugger. (The latest one that haxelib downloads is 1,0,4 and seems to be incompatible with TiVo/intellij-haxe).
When I execute the application from IDEA without debugging (play button), the debugger runs normally, and I can use it from console in IDEA. 

As long as I don't have any breakpoints set, the same happens when I run it through the debugger (green bug button in IDEA).
However, when I execute it through the debugger (green bug button) I get the following error: "Address already in use".

![idea13-address-in-use](https://cloud.githubusercontent.com/assets/421051/5425770/bef0d70e-82f2-11e4-9949-a29e43b589e1.png)

Nothing is revealed when I scroll in the direction of the red bubble.

If I try to set a breakpoint at this time, IDEA freezes completely. Similarly, it freezes even when I try debugging on the first try with a breakpoint set.

TIR: STB-7305

**Comment by EBatTiVo** [comment]
Srikanth says that he fixed this with change https://github.com/TiVo/intellij-haxe/commit/d3a50cd644a8aea271df263dfba3b9f4b38c14cb, which is included in the 0.8.1.1.TiVo.ClassHierarchy.10 or greater builds.

**Comment by ihamer** [comment]
I don't think this works. I tested ClassHierarchy.10 on Mac, Win and OS X. See my comments in #76. Maybe I am doing something wrong? Should I post my (very basic) project here, so someone can look at it?

**Comment by sganapavarapu1** [comment]
I tested my fix only on Linux. 
Yes, please post your minimal project - I can take a look at it.

FYI, my configuration:

IntelliJ IDEA 13.1.6
Build# IU-135.1306, built on Nov 12, 2014
JRE: 1.6.0_41_b02 i386

Lime tools 1.5.6
Haxelib 3.1.0-rc.4
Haxe Compiler 3.1.3
CentOS 6.6, Linux 2.6.32-504.1.3.el6.x86_64 #1 SMP

**Comment by sganapavarapu1** [comment]
Haxe plugin 0.8.1.1.TiVo.ClassHierarchy.11: (community version, TiVo RC1)

if you're using Haxe plugin 0.8.1.1.TiVo.ClassHierarchy.10 --- that's okay too.

**Comment by ihamer** [comment]
@sganapavarapu1
This is my test project: http://s000.tinyupload.com/?del_id=27162404768214120023

Ubuntu 14.04 LTS
Idea 13.1 135.1306
Java-1.7.0-openjdk-amd64
Haxelib 3.1.0-rc.4
Haxe Compiler 3.1.3
Lime Command-Line Tools (2.0.6)

**Comment by sganapavarapu1** [comment]
There's one more change we had to do when we migrated to Haxe 3.1.3.
Haxe compiler changed how filename map key strings are generated... these key strings are used by debugger as well. We had to fix 'gencpp.ml'.

In below function...

let hx_stack_push ctx output clazz func_name pos =
   if (ctx.ctx_debug_level > 0) then begin
   let stripped_file = strip_file ctx.ctx_common pos.pfile in
   let qfile = "\"" ^ (Ast.s_escape stripped_file) ^ "\"" in
	ctx.ctx_file_info := PMap.add qfile qfile !(ctx.ctx_file_info);
      if (ctx.ctx_debug_level > 0) then begin
      let hash_class_func = gen_hash 0 (clazz^"."^func_name) in
      let hash_file = gen_hash 0 stripped_file in begin
		output ("HX_STACK_FRAME(\"" ^ clazz ^ "\",\"" ^ func_name ^ "\"," ^ hash_class_func ^ ",\"" ^
                clazz ^ "." ^ func_name ^ "\"," ^ qfile ^ "," ^
			    (string_of_int (Lexer.get_error_line pos) ) ^  "," ^ hash_file ^ ")\n");
        ctx.ctx_last_stack_line_dumped <- -1;
           end
      end
   end
;;

we fixed, 
	ctx.ctx_file_info := PMap.add qfile qfile !(ctx.ctx_file_info);
to be,
	ctx.ctx_file_info := PMap.add stripped_file qfile !(ctx.ctx_file_info);


You may need to do same your copy of gencpp.ml in haxe compiler (if you are using C++ target) or genswf{9}.ml (if using flash target) etc.,

**Comment by ihamer** [comment]
There is no such line in gencpp.ml. The one I see is:
ctx.ctx_file_info := PMap.add stripped_file pos.pfile !(ctx.ctx_file_info);
Should I change pos.pfile into qfile?

Are you planning on having a proper fix for this inside issue inside the plugin, or will this be fixed in Haxe compiler?

**Comment by grisevg** [comment]
Also Freezes on IntelliJ IDEA Ultimate 14.1.3 and intellij-haxe 0.9.4p1, same behaviour

**Comment by CanIGetaPR** [comment]
Can't reproduce debugging bunnies with breakpoints on IDEA 2024 and plugin version 1.5.3 Flash target.
