### ISSUE TITLE
Standard types aren't resolved when multiple source directories appear in SDK class path.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#770]
To be more specific, it's when the path to std is not the first path in the SDK's Sourcepath list.

Confirmed on Linux, Windows.
Plugin Version 1.0.0
IDEA Version 2017.2, 2017.3

![image](https://user-images.githubusercontent.com/12093217/37436800-06d596fc-27a7-11e8-9e72-198c260c67b5.png)

**Comment by mayakwd** [comment]
I have not idea why anyone even want to setup sdk like this
