### ISSUE TITLE
Autocomplete does not work for List elements and abstract classes

### ISSUE THREAD

**Issue by RedHead90** [HaxeFoundation/intellij-haxe#772]
```
var list:List<Something> = new List();

for(element in list) {
    element. //no code tips here
}
```
This does not work, because the List.iterator() method returns a exemplar ListIterator<T>. If I change it to an Iterator<T>, then the autocomplete starts working.

```
@:forward
abstract AbstractWrapper<T>(T) from T to T {
    public inline function new(value:T) this = value;
}

var obj:AbstractWrapper<Something> = new Something();
obj. //no code tips here
```

These problems are not present if you enable the checkbox Use compiler in the SDK settings.

**Comment by mayakwd** [comment]
Iterators already fixed in the EAP build, second issue still reproducing.

**Comment by EricBishton** [comment]
Tweaking the code a bit gives some of the functionality:
```haxe
package ;

@:forward
abstract AbstractWrapper<T>(T) from T to T {
    public inline function new(value:T) this = value;
    public function extraFunctionality() : T {return this;}
}

class TestIssue772 {
    public function new() {
        var obj:AbstractWrapper<String> = new String();
        obj.      //no code tips here
    }
}
```
![image](https://user-images.githubusercontent.com/12093217/48245196-993c3d80-e39e-11e8-819c-dfc499c656ad.png)

As you can see, functions defined within the AbstractWrapper are available for completion.  However, I think the disconnect is that we don't process the `to` functionality when we walk the class hierarchy looking for candidates.

**Comment by RedHead90** [comment]
Sorry for my English. I`m really looking forward to this fix. And now it has become even more critical, because in Haxe 4 preview versions, Null<T> has also become an abstract type. Now he looks exactly like my example and autocomplete does not work even for such trivial things as Null<String>.

**Comment by EricBishton** [comment]
Will be in release 1.2.
