### ISSUE TITLE
Incompatible type Function

### ISSUE THREAD

**Issue by Deirel** [HaxeFoundation/intellij-haxe#773]
For this:

```
var callback:Function = function():String {
    return "test";
};
```

IDEA gives the error "Incompatible type Function can't be assigned from Void -> String"

Intellij IDEA 2017.2.3, plugin version 1.0.0

**Comment by Gama11** [comment]
There is an abstract named `Function` in `haxe.Constraints` (`import haxe.Constraints.Function;`):

https://try.haxe.org/#218AB

https://api.haxe.org/haxe/Function.html

**Comment by EricBishton** [comment]
Also, it looks like Void->String isn't being fully typed correctly.  :/

![image](https://user-images.githubusercontent.com/12093217/48287885-3dfe5f80-e41f-11e8-81a0-d2d7364b2483.png)

**Comment by olinkirkland** [comment]
I'm having this problem in 1.2. I'm using Haxe 3.4.4.
