### ISSUE TITLE
All imports are broken

### ISSUE THREAD

**Issue by VirtualMaestro** [HaxeFoundation/intellij-haxe#774]
After an update, all imports are now broken (grey highlight). Standard libraries are imported well, but the third party no. The new version was tested on Windows and Mac machines with the latest version of Idea - result the same. (just attached some screenshot as an example).
Thank you
![haxe-plugin-issue](https://user-images.githubusercontent.com/426870/37532598-c04be890-293f-11e8-83b6-abf65c05837c.jpg)

**Comment by dkolyesnik** [comment]
I have the same issue, using Idea 2017.3.5 and plugin 1.0.0. Haxe 4.0.0 preview 3. Windows 10
Project settings are set to HXML (Compile with)
It does not see haxelib libraries added in hxml. I can build project, but it highlits all classes and imports as unknown. And autocompletion is not working for them of course.

**Comment by EricBishton** [comment]
As a side comment to @VirtualMaestro: `import Std;` should never be necessary.  If that makes resolving standard types work correctly, then the Haxe SDK is incorrectly set up.  (Currently, proper resolution only works when the source path has the .../std library as the first entry -- see #770 .)

@VirtualMaestro , @dkolyesnik -- Can you both provide the contents of your project (hxml, nmml, xml) files and your module settings? (Screenshot is OK for module settings.) -- Thanks

**Comment by VirtualMaestro** [comment]
@EricBishton thank you for the answer. I put import Std just to see if Idea sees it. I've attached project.xml and screenshots of module settings (also 'iml' file itself). Just tell me if you need more data.
Thank you  

[project_files.zip](https://github.com/HaxeFoundation/intellij-haxe/files/1820714/project_files.zip)
![module-screen-1](https://user-images.githubusercontent.com/426870/37543323-76b72240-2961-11e8-88f9-61f334aee431.jpg)
![module-screen-2](https://user-images.githubusercontent.com/426870/37543325-76d6ed8c-2961-11e8-8ebf-78736e61adc8.jpg)
![module-screen-3](https://user-images.githubusercontent.com/426870/37543326-76f24f6e-2961-11e8-98b6-e04d451ca220.jpg)

**Comment by dkolyesnik** [comment]
![screenshot_4](https://user-images.githubusercontent.com/8667754/37544291-85b36448-2975-11e8-8f01-e989d13b51d0.png)
![screenshot_5](https://user-images.githubusercontent.com/8667754/37544310-999ada18-2975-11e8-86c6-175477ea1d4a.png)

**Comment by dkolyesnik** [comment]
I haven't used idea with haxe before, so I'm not sure that this setup should work :)

**Comment by cmandlbaur** [comment]
I have the same issue on IntelliJ Ultimate 2017.3.5 running on MacOS HighSierra using Haxe 3.4.6. I am not using an hxml file for my project, just using IntelliJ Project & Module config.

Classes imported from other Modules within my project and the SDK resolve fine.

Classes from External Libraries simultaneously get marked as unresolved and imports are greyed out as unused imports.

**Comment by cmandlbaur** [comment]
`using Lambda;` is also sad

**Comment by mayakwd** [comment]
@cmandlbaur, @VirtualMaestro, @dkolyesnik 
Can you guys please press "Edit" button at the right of sdk name and write down here settings you have there: class-paths and source-paths?

**Comment by cmandlbaur** [comment]
![screen shot 2018-03-19 at 10 14 20](https://user-images.githubusercontent.com/1900059/37584484-57ff6ff2-2b5e-11e8-93f4-577d87cae58a.png)

**Comment by cmandlbaur** [comment]
[LibTest.zip](https://github.com/HaxeFoundation/intellij-haxe/files/1824636/LibTest.zip)
Test project thats broken my side.

**Comment by dkolyesnik** [comment]
I created a new test project using hxml, it has same issues as a real project:
It does not see libs from haxelib, but it compiles without errors.
And also it copy all .hx files to out/production folder, for some reason.
[TestIdea_libs.zip](https://github.com/HaxeFoundation/intellij-haxe/files/1824755/TestIdea_libs.zip)

**Comment by dkolyesnik** [comment]
and here is my SKD settings
![screenshot_6](https://user-images.githubusercontent.com/8667754/37593271-6d9a0e8e-2b82-11e8-800e-52c4d82abf52.png)

**Comment by mayakwd** [comment]
Thank you guys! 
I've fixed this issue, hot-fix will be released in near future.

**Comment by mayakwd** [comment]
Workaround for now - add library paths as source-paths, not as class-paths.

**Comment by ukt** [comment]
@mayakwd 

> Workaround for now - add library paths as source-paths, not as class-paths.

doesn't work for me :( 

Plugin recomended for me to import it, made this import but import still as grey and all as red. 
Compilation still works for source code

**Comment by VirtualMaestro** [comment]
For some reasons it also works partially for me (now it sees openfl lib but doesn't see away3d)
![idea-plugin_2](https://user-images.githubusercontent.com/426870/37681331-b10fb6fa-2c86-11e8-82f1-14a0f251f0b1.jpg)

**Comment by mayakwd** [comment]
There are bug with library updater that introduced with last release, that leads to NPE, will be fixed soon as well.

**Comment by VirtualMaestro** [comment]
Thanks a lot!

**Comment by EricBishton** [comment]
@dkolyesnik - How do you have your h2d library set up?

**Comment by VirtualMaestro** [comment]
Here screenshots of my Away3d settings. 
![idea_plugin_away_settings_1](https://user-images.githubusercontent.com/426870/37849809-5824217a-2ed9-11e8-8b63-cfcb85dd3fb8.jpg)
![idea_plugin_away_settings_2](https://user-images.githubusercontent.com/426870/37849812-5a8ead68-2ed9-11e8-8659-d5f9a399c715.jpg)
![idea_plugin_away_settings_3](https://user-images.githubusercontent.com/426870/37849817-5cdb1e44-2ed9-11e8-8b8f-8b059980bb8a.jpg)

**Comment by mayakwd** [comment]
I assume that it's fixed, if it's not - don't hesitate to reopen issue.

**Comment by emanuel-macoun** [comment]
I'm experiencing similar issues.

Just switched from HaxePlugin 0.11.2 to latest 1.0.2 and imports for all library classes are greyed out.
<img width="463" alt="screen shot 2018-04-25 at 13 44 12" src="https://user-images.githubusercontent.com/29118294/39252025-01447ec8-48a5-11e8-88d1-8db2ac39cb01.png">
This is happening for all library sources.
I have one folder containing those libraries and have it marked as "Sources" in project settings.
<img width="1028" alt="screen shot 2018-04-25 at 16 29 09" src="https://user-images.githubusercontent.com/29118294/39252465-fd64d69e-48a5-11e8-947d-c5f64387cd7b.png">

I noticed that when I mark individual library source root as "Sources" as well, it instantly gets recognized and it's imports are no longer grey.
<img width="1036" alt="screen shot 2018-04-25 at 16 29 30" src="https://user-images.githubusercontent.com/29118294/39253007-2b2a4658-48a7-11e8-8eba-1abbb16b741a.png">
<img width="491" alt="screen shot 2018-04-25 at 16 15 51" src="https://user-images.githubusercontent.com/29118294/39253088-59bb436e-48a7-11e8-919c-b6efab169bea.png">

Obviously, I could go and mark that for all libs in my project, but that's not the solution I'm looking for. It would be nice to have the imports working back correctly. Thanks.

My environment:
Plugin version: 1.0.2
IDEA version: IntelliJ IDEA 2017.3.5 (Ultimate Edition), Build #IU-173.4674.33
OS version: Mac OS X 10.13.4
JDK version: jdk 1.8.0_131

**Comment by emanuel-macoun** [comment]
@mayakwd could you please have a look?

**Comment by VirtualMaestro** [comment]
I have also this issue, that's why still use 0.11.2

**Comment by varadig** [comment]
@VirtualMaestro, Me too

**Comment by mayakwd** [comment]
Hi, guys. 
@emanuel-macoun, your workspace configuration is wrong, and it works in previous version of plugin because of the pack of bugs, that made possible to use classes with misconfigured source roots. 

Layout where all libraries have their own separate source roots is a correct solution, that's how IntelliJ Idea works. Previous behavior gave a lot of unexpected errors, warnings and so on.

Right now your project is just misconfigured.

**Comment by mayakwd** [comment]
As a solution we could try to add option to search source roots and configure them automatically, but it's not a case for this issue.
