### ISSUE TITLE
1.0 unable to compile openfl because of the compilation parameter lime "run"

### ISSUE THREAD

**Issue by cjmxp** [HaxeFoundation/intellij-haxe#775]
1.0 unable to compile openfl because of the compilation parameter lime "run"

**Comment by EricBishton** [comment]
The plugin used to use "lime build" and then "lime test" (which caused another build!).   It has been changed to use "lime update" and "lime build" for the compile/make step, and "lime run" for the run/debug step.

I am unsure of the problem you are seeing.  Can you please capture the output of the messages pane and paste it here?  (If it's too long, you can add it here as a .zip file.)
Also, a screenshot of your current module settings would be useful, and another of your run configuration.

**Comment by CanIGetaPR** [comment]
Should this be closed since we didn't get reproduction steps?

**Comment by EricBishton** [comment]
Well, two and a half years down the road... I guess that makes sense.
