### ISSUE TITLE
Refactoring does not work correctly.

### ISSUE THREAD

**Issue by RedHead90** [HaxeFoundation/intellij-haxe#776]
When I move a file to another package (using the project tool window), the imports in other classes do not change to a new path.
Also, when I rename a class file, the keyword 'new' changes to the class name and breaks the constructor of that class.

Haxe Toolkit Suppor 1.0.0
Idea 2017.3.5

**Comment by EricBishton** [comment]
The second half of the reported issue (Also, when I rename...'new' changes...) is fixed by #922.
