### ISSUE TITLE
Autocomplete for constrained type parameters

### ISSUE THREAD

**Issue by Deirel** [HaxeFoundation/intellij-haxe#786]
In this case autocomplete doesn't work, also here is a warning:
```
function test<T:(DisplayObject, ISomeInterface)>(target:T):Void {
    trace(target.parent); // Warning: Unresolved symbol
}
```

**Comment by m0rkeulv** [comment]
based on my testing, i am considering this issue resolved in the latest version. please re-open the issue if i am mistaken
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/8e87c6ac-e5a1-43e4-81b5-ea0dad857bae)
