### ISSUE TITLE
Parser is stumbling at array access to array declaration

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#787]
The code below produces parsing warning: `,` expected, got `[`
```haxe
class Test {
  static function main() {
    trace([1, 2, 3, 4, 5][3]);
  }
}
```

**Comment by m0rkeulv** [comment]
As far as i can tell this is no longer an issue, so i am closing this one
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/c99b8f9f-97dc-4833-aca3-7efcad8161b9)
