### ISSUE TITLE
Parsing failures for certain cases of "@meta" and "@:pos"

### ISSUE THREAD

**Issue by ericfillipe1** [HaxeFoundation/intellij-haxe#81]
![haxe](https://cloud.githubusercontent.com/assets/4976223/5430005/c0273d14-83e9-11e4-91fb-bb6eaadb0066.png)

TIR: STB-7307

**Comment by EBatTiVo** [comment]
Verified this is broken on the ClassHierarchy branch.

**Comment by michaelmitchell** [comment]
This also stops code completion working for anything under neath the error in the same block for me, quite frustrating.

**Comment by as3boyan** [comment]
I tried adding `private statement ::= macroClassList? (blockStatement | notBlockStatement)` but it requires changes

from 
`whileStatement.getBlockStatement()`
to
`whileStatement.getBlockStatementList()`

**Comment by EricBishton** [comment]
Fixed by 157ccce2f2491a4ebe1574f0729c9ee010e66743
