### ISSUE TITLE
Haxe 4: Allow 'enum abstract' syntax

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#810]
See HaxeFoundation/Haxe#6982.

**Comment by EricBishton** [comment]
@mayakwd I know you did some work in this area.  Do we have complete support now?

**Comment by mayakwd** [comment]
Yep it's supported, added with https://github.com/HaxeFoundation/intellij-haxe/pull/883

**Comment by EricBishton** [comment]
Will be released in 1.1.0.
