### ISSUE TITLE
local .haxelib is supported? 

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/intellij-haxe#813]
Hello, 

Is the local haxelib folder `.haxelib` create with `haxelib newrepo` supported by **intellij-haxe**? 

I'm using Haxe plugin 1.0.2 with Intellij 2018.1.2 and `hxml` compilation. 
In `hxml` files, I use `-lib` that are installed in the local folder `.haxelib`. 

Libs are found during compilation, but it looks like none are available in IDE. 
* cannot find declaration to go to (when I try to go to declaration)
* no auto-completion
* unresolved symbole in import

**Comment by aliokan** [comment]
This manual solution is really painful on project that use a lot of dependencies. 
Paths should be fixed each time a lib version is changing. 

It will be a real improvement if libs resolution is resolved by the compiler from hxml

**Comment by EricBishton** [comment]
I agree that it will be a real improvement.  Full support of project files has been in the plan for a while now and we are making incremental improvements as we go along.  Local haxelibs are also on my list of things to work on Real Soon Now; I have looked into it and the way haxelib deals with them is not consistent, which is going to cause some convoluted logic in the IDE.  (Try doing `haxelib info lib` when you have local and global repositories vs when you only have one or the other.)

**Comment by m0rkeulv** [comment]
Latest version will detect if there's a local repo in project root (`.haxelib`) and use libs from this repo.
(the plugin runnings  `haxelib config` with project root as workdir to get the repo  to use.)
