### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by varadig** [HaxeFoundation/intellij-haxe#818]
Hi, I don't know is a intellij plugin related issue or not but when I wanted to build my project (cpp/html5/flash...etc) I got this error:

https://www.dropbox.com/s/4o0w6q1qka7mf29/Screenshot%202018-05-04%2009.21.04.png?dl=0

with openfl test html5/flash/cpp..etc is working and I can compile the project.

**Comment by varadig** [comment]
I use this version:
https://www.dropbox.com/s/gj0pelg7jpxw13h/Screenshot%202018-05-04%2009.30.17.png?dl=0

**Comment by mayakwd** [comment]
@varadig Please open Haxe Sdk settings and setup neko executable path, and haxelib executable path as well. Open module settings: press F4 when standing on the module root in the Project structure window (Alt+1), press "edit" button near the Module Sdk dropdown, and setup paths (you can use browse buttons [`...`].

For default paths: 
neko: `%YourHaxeToolkitPath%\neko\neko.exe`,  and 
haxelib: `%YouHaxeTookitPath%\haxe\haxelib.exe`

For example:
`C:\HaxeToolkit\neko\neko.exe`
`C:\HaxeToolkit\haxe\haxelib.exe`

In the module settings you can choose target platform at the tab `Haxe`, where you can find compilation settings.

**Comment by varadig** [comment]
@mayakwd Thanks!

After I set the paths, and try to compile got this:
https://www.dropbox.com/s/zwg0qvqui9ikzyy/Screenshot%202018-05-04%2009.53.48.png?dl=0

**Comment by varadig** [comment]
https://www.dropbox.com/s/cuqy5z2elh6bz5w/Screenshot%202018-05-04%2009.58.05.png?dl=0

**Comment by mayakwd** [comment]
@varadig Ahha, that's a common error for Mac users. You need to add HAXE_STD_PATH environment variable to your `~/.bash_profile`
`export HAXE_STD_PATH=/usr/local/lib/haxe/std/`
Check this issue for more details: https://github.com/HaxeFoundation/intellij-haxe/issues/762

**Comment by varadig** [comment]
@mayakwd and start app from commandline, and it's working ;) thanks!
