### ISSUE TITLE
Project fails to launch after compile for IDEA 14

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/intellij-haxe#82]
I'm compiling a very basic OpenFL project, it compiles fine, but then nothing else happens.
I would expect the project to open in chrome using the build in webserver or within the flash player, is this what is meant to happen? or am I missing something fundamental here?

I'm testing OpenFL with both flash and html targets
and using IntelliJ IDEA 14 Ultimate

**Comment by EBatTiVo** [comment]
Duplicate of #66?  This bug is for OpenFL, #66 is for Neko.

**Comment by sganapavarapu1** [comment]
I'm able to launch and debug my application in IntelliJ IDEA 14.1.1 build 141.178 Ultimate edition
(openfl with lime toolchain for cpp target on linux centos 6.5)

**Comment by CanIGetaPR** [comment]
Can't reproduce with openfl bunnymark sample and plugin version 1.5.3 and IDEA 2024.
