### ISSUE TITLE
Easier SDK setup

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#820]
- [x] Auto-detect Haxe SDK (by default paths)
- [x] Auto-setup of haxelib and neko executables

**Comment by DanMan** [comment]
While we're at it: the setup dialog seems very Windows centric. It asks for a "Haxe toolkit home path", but it's really just the path to the `haxe` binary, which (at least here on Ubuntu) is `/usr/bin`. It's confusing: https://stackoverflow.com/questions/26545849/intellij-does-not-recognize-haxe-sdk

**Comment by RealyUniqueName** [comment]
Auto-detecting Haxe SDK and neko executable is implemented in #856

**Comment by RealyUniqueName** [comment]
Haxelib executable is also detected correctly after #856 
So I think this issue is resolved.
