### ISSUE TITLE
Plugin wrongly accepting comma separated fields that the compiler wont.

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/intellij-haxe#83]
``` haxe
private var field1:Int, field2:String;
```

is fine for the plugin, but haxe compiler says: characters 37-38 : Unexpected ,

TIR: STB-7309

**Comment by as3boyan** [comment]
This was fixed I think, http://try.haxe.org/#1019f

I posted issue similar to this to Haxe repository, Nicolas said this https://github.com/HaxeFoundation/haxe/issues/4175

Should work properly in upcoming 0.9.4.

**Comment by as3boyan** [comment]
Local variable declarations can have multiple vars/fields.
Class level variable declaration can have only single var/field.

**Comment by mayakwd** [comment]
Fixed along the way with other fixes.
