### ISSUE TITLE
No Completion on Result of Brackets

### ISSUE THREAD

**Issue by cmandlbaur** [HaxeFoundation/intellij-haxe#830]
Currently running on ultimate 2018.1.4 EAP with latest plugin build(1.0.2.dev.3ea6747)

```haxe
"banana".replace("na", "ba"); // Resolves
var apples = "apples";
apples.replace("app", "abb"); // Resolves

("banana" + "apples").replace("a", "o"); // Doesn't Resolve
("banana" + "apples").indexOf("a"); // Doesn't Resolve
("apples").indexOf("a"); // Doesn't Resolve
```

**Comment by m0rkeulv** [comment]
seems to resolve fine in latest version
 (`replace` requires  `using StringTools` though )
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/e40f0f4d-a0c8-469a-bd34-0c8f2cf5d5b2)
