### ISSUE TITLE
Automatic import placed after class Doc comment.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#842]
Imports should come before leading comments for a class.  (Especially doc comments.)

To reproduce:  Auto-add the import for openfl.system.System by pressing Alt+Enter at line 19.

![image](https://user-images.githubusercontent.com/12093217/40218865-ef858fee-5a27-11e8-99aa-647b0e65c59e.png)

IDEA Version: 2018.1
Plugin Version: 1.0.2 for 2018.x
Develop branch: e19d288d

**Comment by Gama11** [comment]
Note that when you fix this, you need to consider license headers too. It maybe be hard to tell whether a comment belongs to the type or not in some cases, as there may not always be a `package` statement.

**Comment by EricBishton** [comment]
True enough.  We *do* know the difference between a regular comment and a doc comment (.e.g /**).  Doc comments placed immediately in front of another primary element (class, field, method) should be associated with the primary element, in all cases.  Doc comments should not be used in imports, though users could do that.  However, the current implementation checks that import sections don't contain any comments; if they do, we refuse to sort them.
