### ISSUE TITLE
Highlight an error if type identifiers do not start with upper case

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/intellij-haxe#85]
``` haxe
    public function gotoAndPlay(frame: string) { this.seek(frame); this.play(); }
```

This produces a warning unresolved type "string", but should produce an error because string is an invalid type name because it doesn't start with a case. It should be "String".

**Comment by EBatTiVo** [comment]
> Types should start with case

I get your point here, but I don't agree.  It's not the IDE's job to enforce programming style.  On the other hand, I think you really mean that the type ``` string ``` isn't a known type, so should display as unresolved -- which it does (at least in the ClassHierarchy branch).  If you highlight the unresolved symbol and press Ctrl+space to get suggestions, the type ``` String ``` shows up in the list.  If what you want is auto-correction to known types, then I think that's just going to create a different set of bugs: How is the IDE supposed to know that you didn't really mean to include a missing library with a custom ``` string ``` type?

So, I don't think there's a bug here.  Re-open if you disagree.

```haxe
class Issue85Test {
    public function gotoAndPlay(frame: string) {
        this.seek(frame); 
        this.play(); 
    }
}
```

**Comment by soywiz** [comment]
I was porting a code from typescript to haxe, and I noticed that it was not producing an error, but just a warning and the compiler doesn't treat it that way.

@EBatTiVo 
I don't think it is a coding-style issue, but a feature/language design detail:

File:
test.hx
```haxe
package;
class test {
        static public function main() {
        }
}
```

Compiler output:
```
haxe -main test
Error: Could not process argument test
Class name must start with uppercase character
```

-------------

Test2.hx
```haxe
class Test2 {
        static public function main():Int {
        }
}
```

Compiler output:
```
haxe -main Test2.hx
Test2.hx:2: lines 2-3 : Missing return Int
or changing with :Int2
Test2.hx:2: lines 2-3 : Class not found : Int2
or chaning with :int
Test2.hx:2: characters 35-36 : Unexpected {
```

```
haxe -version
3.1.3
```

**Comment by EBatTiVo** [comment]
I guess we could quibble about which is the more appropriate message -- and possibly whether an unresolved type should be marked as an error, rather than a warning.  I still don't think that the editor should be automatically coercing the case, though.

Perhaps the BNF should restrict Class/Type identifiers to have leading case, and not use a single unified identifier definition that it does now?

At any rate, re-opening as an enhancement.

**Comment by soywiz** [comment]
I wouldnt do that in the bnf. I think they do in the compiler just trying to match a type and that produces that awful error.

I don't know which phases the plugin has. But I would do that later after the bnf. You allow any valid identifier. Then validating the ast you can check type names and yield errors when the first letter is not uppercase. Not just when referencing types but also on type declarations:
class invalid {}
class Test extends invalid implements invalid {}
...
That would provide feedback early about this kind of errors and would save lot of time later executing the compiler.

**Comment by EBatTiVo** [comment]
I haven't seen a second pass validating the AST.  Almost all of the errors come out of the parsing phase.  (JFlex generates the parser and scanner, and there's a minimal lexer.)

I suppose we could check the identifier value as the AST/PSI elements are constructed.  I'm not sure how to signal the error on screen, but there's probably a way...

So, why not do it in the BNF?  I think that we can customize the error output into something reasonable.  (I saw something about that in the overly-dense Grammar-Kit docs.)

**Comment by Simn** [comment]
The casing actually influences type path parsing. I try to keep it simple:

* If it starts with a lowercase character it must be a package name and the parser expects a `.` followed by the next part of the type path.
* If it starts with an uppercase character it must be a type name. At this point the parser accepts _one_ additional `.` followed by an _uppercase_ identifier in order to parse module sub-type access (e.g. `Expr.ExprDef`).

```
parse_type_path1 ::= lower_ident "." parse_type_path1 | upper_ident ["." upper_ident]
```

**Comment by EricBishton** [comment]
Somewhere along the line, Carlos (soywiz) fixed this.  Thanks, Carlos.

And, for the record: I was wrong about the type having to be Capitialized.  I figured that out somewhere along the line, too.
