### ISSUE TITLE
Poor performance when using Nape

### ISSUE THREAD

**Issue by Matan** [HaxeFoundation/intellij-haxe#851]
Hi!

When using the nape physics library, the IDE really loses a lot of performance. Type completion, reference finding, organizing imports (esp bad, ide hangs for a few minutes at 100% cpu), even highlighting of keywords pauses for a while.

Create sample project, link up Nape and start using the Body (try opening the class as well) class or any of Nape's classes.

Been using this plugin for years and it's been great! Just seems to struggle with Nape. Any insights would be greatly appreciated.

Thanks!

**Comment by EricBishton** [comment]
Hi Matan,  You're using a mac, right?  Do you know when this started happening (which version), or has it always been slow with Nape?

**Comment by Matan** [comment]
Hi Eric! I'm on Ubuntu 18.04 using the latest Snap installation of Intellij Ultimate with latest version of the plugin. I haven't used Nape is quite a while, so not sure when this started.

I've got a moderate speed improvement by using code completion from the compiler. It also seems to help if I try and reduce the code context by adding: `haxe3` and `NAPE_RELEASE_BUILD` flags to the project settings. I can see these are used in the Nape source code.

**Comment by mayakwd** [comment]
@Matan, Hi! Could you please provide example setup of the project? I want to figure out if this issue is still exists.

**Comment by EricBishton** [comment]
The setup was simple: Install nape as a haxelib, add it to your project, and go to a source file with over a thousand lines in it. (There are several within nape itself.)  Then notice that CPU usage goes way up and typing gets very sluggish.  It took several minutes for the background  annotations to display and CPU usage to go down. Of course every character change started the sequence again.  The problem was actually more pronounced on MacOS for some reason.

**Comment by Matan** [comment]
Hey Guys! Using latest intellij 2018.2.4 with plugin 1.0.2 looks a lot better! I haven't been working on a Haxe project for a while. Open the last nape project and run an organize imports on class I knew to be problematic. The first organize capped my CPU for about 30 seconds, now everything is lightning! :grin:

**Comment by EricBishton** [comment]
Fixed by #859.  Will be released in 1.1.0 build.
