### ISSUE TITLE
Imports incorrectly assessed as "unused" when referenced via type name or as a variable type.

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/intellij-haxe#86]
It seems that imports are detected just when calling new Class, but not when referenced as :Class or calling static methods.

``` haxe
new Class(); // <-- referenced
Class.staticMethod(); // <-- not referenced
function method(ref:Class) {} // <-- not referenced
```

TIR: STB-7310

**Comment by mayakwd** [comment]
Not reproducible

**Comment by EricBishton** [comment]
Also not reproducible any more.  Fixed somewhere along the way...
