### ISSUE TITLE
Haxe 4: Allow enum values as constants for function args

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#871]
See https://github.com/HaxeFoundation/haxe/issues/4287.

Not sure whether the plugin disallows this or not.

**Comment by m0rkeulv** [comment]
I believe  the  plugin (develop branch)  behaves correctly
intelliJ haxe:
![image](https://user-images.githubusercontent.com/3193925/98472614-7d214000-21f4-11eb-8e4e-48e0b23093cc.png)

HaxeDevelop/compiler results
![image](https://user-images.githubusercontent.com/3193925/98473054-397b0600-21f5-11eb-99f9-ffe797b60d27.png)

**Comment by m0rkeulv** [comment]
This looks like it has been solved so i am closing this one.
