### ISSUE TITLE
Haxe 4: Use `[]` to initialize empty map.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#874]
New syntax is allowed for initializing empty maps.

See https://github.com/HaxeFoundation/haxe/issues/7426 and https://github.com/HaxeFoundation/haxe/commit/dda4521002b38b0b0816dcf03c369ced5b063056.

**Comment by Gama11** [comment]
I think the syntax that's been allowed is just `[]`, not `[=>]`.

**Comment by EricBishton** [comment]
You're right.  That's what I get for just reading the email and not looking at the commit.  :/

**Comment by EricBishton** [comment]
Verified that this still exists on 1.3.

**Comment by EricBishton** [comment]
Fixed with PR #1041.  Will be in 1.4 release.
