### ISSUE TITLE
Missing indent (tab) settings page for Haxe language.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#908]
As of release 1.2, the "Other Files" settings page controls tab settings for Haxe files.  The plugin should have (and respect) its own specific settings.

Workaround: Use the Other Files Settings page...

![otherfiletypessettingspage](https://user-images.githubusercontent.com/12093217/51806865-fd4eff00-2233-11e9-98dd-369c55b816fd.PNG)

**Comment by EricBishton** [comment]
Apparently, you can also set and then copy the settings from another language to Haxe using the "Set from..." link in the upper right of the Haxe code style page:

![image](https://user-images.githubusercontent.com/12093217/51807638-4d32c380-223e-11e9-9f5b-b592d01063ff.png)

**Comment by kodekuru** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/11985154/51807707-8fd6b900-229b-11e9-87f3-3b16a604b1e0.png">

Tab settings page issue is resolved if getIndentOptionsEditor function is added to the HaxeLanguageCodeStyleSettingsProvider class.

**Comment by EricBishton** [comment]
Yes and no.  Yes, it is displayed.  No, it doesn't actually apply/change/save the settings just because the page is shown.

**Comment by m0rkeulv** [comment]
Closing this one as its been added in resent versions.
I have verified that toggling the checkbox  and reformatting code  changes between whitespace and tabs
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/6172914d-814e-48c2-b7ec-569bddf1fb26)
