### ISSUE TITLE
Create a project display nothing to show

### ISSUE THREAD

**Issue by crud-boy** [HaxeFoundation/intellij-haxe#918]
Create project -> select haxe-> nothing to show

There seems to be no way to create a project in the wiki. Is this plugin not a one-click fool creation project?

**Comment by EricBishton** [comment]
I'm not sure what you are asking here...  We certainly are not trying to create any fools.  :)

If you are running the plugin in IntelliJ, and you select "File->New->Project...->Haxe", then a dialog appears asking if you want SQL support, which you can check or not, then press "Next", select and/or configure a Haxe toolkit (the plugin does not download it for you, but will attempt to find one already installed), then "Next" to select the project name and directory.  "Finish" will create the project and any directories, add a file called Main.hx and open it in the editor.

Does this really require a Wiki article on the project web site?  Maybe so.  I guess I could write one...

(Note that the github wiki for this project was used for project management.  I have deleted those out-of-date pages.  The project's wiki is at http://intellij-haxe.org.)

**Comment by crud-boy** [comment]
![](https://github.com/crud-boy/temp_file/raw/master/444.png)

How to create a project

**Comment by mayakwd** [comment]
Press "Next" button?

**Comment by crud-boy** [comment]
Why there is no breakpoint debugging function

**Comment by mayakwd** [comment]
Is it relative to issue subject?
