### ISSUE TITLE
Haxe 4.0: Allow '.' in #if expressions.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#919]
For now, it's only available inside of parens:  `#if (platform.test>1.0.0)`

`#if platform.test` and `#if !platform.test` should eventually work without parens, but might not make it into 4.0.

**Comment by nadako** [comment]
Looks like it made it to Haxe 4 :)

![](https://i.imgur.com/vergobo.png)

**Comment by nadako** [comment]
> Looks like it made it to Haxe 4 :)

Wait, this is different, not conditional compilation, but metadata. Still it would be nice to support it, as right now it's pretty broken for us and we can't even just add parens

**Comment by nadako** [comment]
Made a separate issue about the metadata part #955, so I can link to it as it's quite important for us at InnoGames.

**Comment by EricBishton** [comment]
Fixed by #962.
