### ISSUE TITLE
Support for 2019.x versions

### ISSUE THREAD

**Issue by Mansfield92** [HaxeFoundation/intellij-haxe#920]
It's obvious from the title, that current version of toolkit is incompatible with new 2019.1 version. It would be good to be able to prevent this inconvenience in the future versions.

**Comment by ukt** [comment]
Hello, do we have some progress with this. or expected release time?
Thank you.

**Comment by EricBishton** [comment]
Fixed with #925 (develop branch).  A new release will be out shortly.

**Comment by cmandlbaur** [comment]
Hi Eric, do you have a gut feel for when a build will be available?

**Comment by EricBishton** [comment]
Hi Chris,
I've been trying to get a release for a couple of days.  I ran into issues during the smoke test and had to fix them.  I've fixed those now, so if the smoke tests all go well tomorrow, then I'll get one out then.

**Comment by Mansfield92** [comment]
Hi @EricBishton, is there any progress on the build?

**Comment by damoebius** [comment]
Do you plan a new release soon ? Actually it's still impossible to install the plugin on the 2019.1 version

**Comment by demurgos** [comment]
As a workaround you can clone the repo, edit the `Makefile` to set the version to `2019.1.3`, build the plugin (`make`) and install it from disk. Still, I hope that the version on the Jetbrains repo version will be updated.

**Comment by EricBishton** [comment]
It is easier than that.  The instructions are in the CONTRIBUTING.md file.

Basically, clone the repo, open the project in IntelliJ IDEA, and build using the normal build commands there.

Yes, I know folks are waiting (more or less) patiently.  I am still working on this.  I haven't released it because flash debugging isn't working.  It's either my environment or a subtle change.  I promise I'm chasing it, and as soon as I can, it will be released on the JetBrains plugin repository.

**Comment by cmandlbaur** [comment]
For what it’s worth there’s a team of people on my end who are not working at all with Flash. No pressure, just saying it might not be an issue for everyone.

**Comment by Mansfield92** [comment]
For anyone too lazy to do it himself (or not working on Ultimate Edition), you can download build and install it manually. It worked for me and my colleague, but I can't promise it will work for everyone. [package for 2019.x](https://uploadfiles.io/vxfm4pqf)

**Comment by EricBishton** [comment]
For those watching this issue: it's been released!

**Comment by emanuel-macoun** [comment]
Wo-Hooo ! Thanks a lot.
