### ISSUE TITLE
Openfl UTF8String type not recognized since update for intelliJ 2019

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#941]
**Affected version: 1.2 for IDEA 2019.x**
**OS: Windows
IDE: IDEA Ultimate 2019.2**

This error started happening after I upgraded to the 2019 version of the plugin, from the 2018 one.

![image](https://user-images.githubusercontent.com/45294513/62299292-ac1e0300-b442-11e9-9c93-7b07dfcb917d.png)

> UTF8String is an abstract that allows implicit conversion from String

**Comment by EricBishton** [comment]
Looks like a bug in the new error detection code.  UTF8String is defined in lime as:
```Haxe
abstract UTF8String(String) from String to String {...}
```

Either the from/to detection is failing or the type compatibility checking is not resolving the String reference properly.

**Comment by CanIGetaPR** [comment]
line 883 there's the checking if something can be assigned

`  public static void check(HaxeAssignExpression psi, HaxeAnnotationHolder holder) {
    // TODO: Think about how to use models to do this instead. :/
    PsiElement[] children = psi.getChildren();
    PsiElement lhs = children[0];
    // PsiElement assignOperation = children[1];
    PsiElement rhs = children[2];

    HaxeGenericResolver resolver = HaxeGenericResolverUtil.generateResolverFromScopeParents(psi);
    ResultHolder lhsType = HaxeTypeResolver.getPsiElementType(lhs, psi, resolver);
    ResultHolder rhsType = HaxeTypeResolver.getPsiElementType(rhs, psi, resolver);

    if (!lhsType.canAssign(rhsType)) {
      HaxeAnnotation anno = typeMismatch(rhs, rhsType.toStringWithoutConstant(), lhsType.toStringWithoutConstant())
        .withFixes(HaxeExpressionConversionFixer.createStdTypeFixers(rhs, rhsType.getType(), lhsType.getType()));
      holder.addAnnotation(anno);
    }
  }`

**Comment by CanIGetaPR** [comment]
Specifically the code here,

HaxeTypeCompatible.java

`Set<SpecificHaxeClassReference> compatibleTypes = to.getCompatibleTypes();
    for (SpecificHaxeClassReference compatibleType : compatibleTypes) {
      if (compatibleType.toStringWithoutConstant().equals(from.toStringWithoutConstant())) return true;
    }`

 `   compatibleTypes = from.getInferTypes();
    for (SpecificHaxeClassReference compatibleType : compatibleTypes) {
      if (compatibleType.toStringWithoutConstant().equals(to.toStringWithoutConstant())) return true;
    }

    return to.toStringWithoutConstant().equals(from.toStringWithoutConstant());`

**Comment by EricBishton** [comment]
Before you go too far down this path, know that I've spent the last month working through issues in exactly this code.  I am very close to making a PR.  My last issue (before your reports, of course) is getting chained generics and abstracts to compare properly.  Basically, KeyValueIterators are still popping up errors.

If you want to play around with (test, debug, etc.) with my fixes, I can check them in to my fork and you can get ahold of them there.  Let me know whether I should do that or you'd rather wait to see them.

**Comment by CanIGetaPR** [comment]
Unfortunately I’m new to haxe and don’t know enough about how it works to contribute or test meaningfully. I was just trying to give you a head start at tracking down the issue, so it’s great to hear you’re already on it.

Thanks!

On Aug 1, 2019, at 6:37 PM, Eric Bishton <notifications@github.com<mailto:notifications@github.com>> wrote:


Before you go too far down this path, know that I've spent the last month working through issues in exactly this code. I am very close to making a PR. My last issue (before your reports, of course) is getting chained generics and abstracts to compare properly. Basically, KeyValueIterators are still popping up errors.

If you want to play around with (test, debug, etc.) with my fixes, I can check them in to my fork and you can get ahold of them there. Let me know whether I should do that or you'd rather wait to see them.

**Comment by CanIGetaPR** [comment]
Unfortunately I’m new to haxe and don’t know enough about how it works to contribute or test meaningfully. I was just trying to give you a head start at tracking down the issue, so it’s great to hear you’re already on it.

Thanks!

**Comment by CanIGetaPR** [comment]
Hey Eric, do you want to check them into your develop branch? I'd love to help expedite fixing this if possible.

**Comment by EricBishton** [comment]
They're already there: See #944

**Comment by EricBishton** [comment]
The problem turned out to be that we didn't expect underscores in a package name.  Added to PR #972.
