### ISSUE TITLE
Can't Use Classes Inside Swf for Autocomplete

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#942]
**Affected versions: 1.1 for IDEA 2018.x ,1.2 for IDEA 2019.x**
**OS: Windows
IDE: IDEA Ultimate 2019.2**

The IDE sees the classes inside a swf but they are unresolved in my code.

![image](https://user-images.githubusercontent.com/45294513/62299604-3f573880-b443-11e9-917f-4cf9c11808d3.png)

![image](https://user-images.githubusercontent.com/45294513/62299694-66ae0580-b443-11e9-8a53-7fa4f1536c18.png)

So auto complete doesn't work. The program runs fine and finds the classes.

**Comment by m0rkeulv** [comment]
This does not make much sense to me. the way i see it these are classes from 2 different languages. Your code is Haxe code and SWF files contains Bytecode/actionscript, If you want to use Classes from a different language you will most likely have to declare them as externs somewhere, or try to mimic what openFl does with its Assets using @:bind and @:native.  you cant just import them directly like your example above.

`@:bind` to overwrite the actionscript declaration when targeting flash/Air
` @:native("ClassName")` does some kind of rewrite of the path to the class.
More info here : https://haxe.org/manual/cr-metadata.html

**Comment by CanIGetaPR** [comment]
Natively supporting OpenFL's swf library is not currently planned.
