### ISSUE TITLE
Plugin No Longer Differentiates var and function types

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#943]
Affected version: 1.2 for IDEA 2019.x
OS: Windows
IDE: IDEA Ultimate 2019.2

This happened after upgrading to version 1.2

It thinks when you're assigning a function, that the function's return type is supposed to match the variable's type of which you're assigning to.

![image](https://user-images.githubusercontent.com/45294513/62301788-38cac000-b447-11e9-822b-68e37f4d760e.png)

Possibly related work: https://github.com/HaxeFoundation/intellij-haxe/issues/579

**Comment by CanIGetaPR** [comment]
Possible duplicate: #773

**Comment by CanIGetaPR** [comment]
It was working fine for me as `public var onAccountEnter:Function = null;` using `openfl.utils.Function;` on v 1.1 I'm sure.

**Comment by EricBishton** [comment]
BTW, thanks for the bug reports,

**Comment by CanIGetaPR** [comment]
> 
> 
> BTW, thanks for the bug reports,

Thanks for all your hard work and doing the god send of making haxe work with the best IDE in the world ♥ ☺
