### ISSUE TITLE
Haxe 4 - Optional field syntax

### ISSUE THREAD

**Issue by Kbam7** [HaxeFoundation/intellij-haxe#950]
**Versions**
Plugin: 1.2 for IDEA 2019.x
IDEA: IntelliJ IDEA 2019.1 (Ultimate Edition) - Build #IU-191.6183.87, built on March 27, 2019
OS: Windows 10 10.0
JDK: 1.8.0_181
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Haxe: Haxe Compiler 4.0.0-rc.3+e3df7a448

Consider the following typedef:
 ```
typedef FullName =
{
    @:optional var name:String;
    @:optional var surname:String;
}
```

This typedef has optional fields as described here https://haxe.org/manual/types-structure-optional-fields.html

There is a new syntax introduced in Haxe 4 and it looks a little like this:
 ```
typedef FullName =
{
    var ?name:String;
    var ?surname:String;
}
```

However, the plugin does not consider this new syntax valid. I have compiled the code and it works fine. Its just the syntax highlighting that is an issue.

**Comment by EricBishton** [comment]
Fixed by PR #1048.  Will be released in plugin version 1.4.
