### ISSUE TITLE
implements ArrayAccess<V> is not supported

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/intellij-haxe#957]
```haxe
extern class Vector<T> implements ArrayAccess<String> {
}

class Main {
    static public function main() {
        var vec = new Vector<String>();
        vec[0]. // <-- this should give completion for String
    }
}
```

When an extern class implements `ArrayAccess<T>` its instances can be indexed using an int key like in the example above and that should return a value of type `T`.

Example in the standard library: `flash.Vector`

**Comment by EricBishton** [comment]
Yeah, this should be working (maybe not with `implements ArrayAccess`, but with anything that actually implements `@:arrayAccess`).  However, there appears to be some general problem with internal completions when running against 2019.2 versions.  Compiler completions still work:

![image](https://user-images.githubusercontent.com/12093217/65984718-3380f600-e435-11e9-9cf3-77f8ac395547.png)

**Comment by EricBishton** [comment]
For supporting ArrayAccess class, also fix HaxeMethodModel.isArrayAccessor() to recognize it.

**Comment by EricBishton** [comment]
@nadako So, if `vec[0].` is an array access expression on an external class, how do we figure out which method that would be?  In the manual, it gives an example where the `extern` functions are marked with `@:arrayAccess`.  But, if there is not a function so marked, and the class extends `ArrayAccess<T>`, how is the method to call determined?  The `ArrayAccess` class (at least in rc.3) does not declare any members.  Are there assumed methods in that case (one for `set`, one for `get`)?  (And, if so, why aren't they declared in the `ArrayAccess` class?)

**Comment by m0rkeulv** [comment]
Since there is no methods  or models to use to determine type, i have added a hackish workaround in the plugin that handles this special case. (these changes are currently only in Dev, but will be included in next release)
