### ISSUE TITLE
Lexers are not being built automatically.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#958]
_HaxeLexer and HXMLLexer still require being (re)built by hand and checked into the source base.  Only the .flex files should remain in the source tree.  The XXXToken files should also be removed from the source tree.

Gradle tasks 'generateHaxeParser' and 'generateHxmlparser' currently build the PSI from the .BNF using Grammar-Kit.  Adding the lexers is very similar.  See https://github.com/JetBrains/gradle-grammar-kit-plugin#generating-lexer.

**Comment by m0rkeulv** [comment]
@EricBishton   
This one was solved in https://github.com/HaxeFoundation/intellij-haxe/pull/1022 i think so this issue could maybe be closed ?

**Comment by EricBishton** [comment]
Indeed.  Thanks.
