### ISSUE TITLE
Method name resolves to Base class when declared class does not have that method.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#968]
When a method name is used, but it isn't available on the declared class (Array in the example below), but it _is_ available on the base class, then the base class method is resolved (used for typing, searching, etc.).

```Haxe
package ;
class ResolveToThisClassParentRatherThanDeclaredClass extends Base{
    public function new() {
        var a : Array<String> = [];

        a.add("new String");  // add Resolves to Base.add when it should be unresolved.  There is no add() in Array.
    }
}

class Base {
    public function new() {}
    public function add(a:String) {}
}
```

**Comment by m0rkeulv** [comment]
Fixed in dev now, 
Bug was that any "unresolved" references would get into the  check class/super block, even if the reference was no variables and not related to class.
