### ISSUE TITLE
Refactor->Introduce Variable re-using existing name and renaming all instances (new and old).

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#969]
When refactoring variables, an existing name was picked and all of their names got changed when typing the new name.

Select the expression to assign to the new variable:
![image](https://user-images.githubusercontent.com/12093217/66897362-b49aca00-efab-11e9-9523-4b40f9d1bd54.png)

Then Refactor:
![image](https://user-images.githubusercontent.com/12093217/66897474-edd33a00-efab-11e9-8657-3a97c322f9f0.png)

Selected name was "anim" which was an already existing variable.

This is happening on the Post1.2 develop branch, using IDEA 2019.2.

**Comment by m0rkeulv** [comment]
Fixed in https://github.com/HaxeFoundation/intellij-haxe/commit/1bd18aec036deaadea1a4aba2ec4a103cd26ffa9 
solution: scan trough method body for used variable names
