### ISSUE TITLE
IDEA 2020.1 Compatibility: Change base class for HaxelibModuleManager to StartupActivity

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#974]
Starting in IDEA 2020.1, plugins won't require the whole app to shut down.  To support this, the "XXXComponent" base classes are being removed.  Using different services or extension base classes is the way forward.  See http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_components.html 

`HaxelibModuleManager` is the only class using the Component system, and it should be re-implemented using a StartupActivity implementation and registered via `com.intellij.postStartupActivity` or `com.intellij.backgroundPostStartupActivity` (preferably, the latter, but it was first introduced in 2019.3, so will not work for earlier versions of IDEA).

**Comment by m0rkeulv** [comment]
current dev branch is implementing `ProjectManagerListener, ModuleListener` instead of using the moduleComponent to detect changes in project/module structure, since we no longer extends the component class i consider this one solved.
