### ISSUE TITLE
IDEA 2020.1 Compatibility: Ensure that intellij-haxe passes compatibility checks.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#975]
Or the repository will show any non-compliance to the user before installation.  See http://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes_list.html

**Comment by cmandlbaur** [comment]
Hi Eric, this seems to be an issue that has become current. Is this something you are looking at now?

Happy to help however I can.

**Comment by EricBishton** [comment]
I haven't started looking at it yet.  I guess I'll have to move it to the top of the priority list.

**Comment by eliasku** [comment]
I made quick and dirty Haxe Support 1.2 built specially for 2020.1:
please check release: https://github.com/eliasku/intellij-haxe/releases/tag/1.2-2020
branch compare against master: https://github.com/HaxeFoundation/intellij-haxe/compare/master...eliasku:quick-support-2020.1

official support would be great :)

**Comment by kledsen** [comment]
@eliasku  That build does not work for me unf.

**Comment by kledsen** [comment]
@EricBishton Anything we can do to help to get this moved along? This plugin is much valued by us, so please just let me know.

**Comment by Sonorpearl** [comment]
I would love to see and update for 2020.1. 👍

**Comment by derRaab** [comment]
@eliasku Thanks for your version. IntelliJ 2020.1 says it's incompatible, but works. Just to let people know that it seems to work fine.

**Comment by kledsen** [comment]
Workarounds don't work for us.
We'll stop using this plugin for good bc of this issue not resolving in any meaningful timeframe,
But thanks for the work here, we liked it while it lasted.

**Comment by derRaab** [comment]
@kledsen will you use VSCode instead?

**Comment by EricBishton** [comment]
https://github.com/HaxeFoundation/intellij-haxe/commit/48fca44f761a69d5d11683af58660bcc47066f13 on the develop branch adds 2020.1 support.  Working on 2020.2...

**Comment by EricBishton** [comment]
https://github.com/HaxeFoundation/intellij-haxe/commit/983af77c0887a7b95a9ab2e83bb6b9509b80c76f adds 2020.2 support.

**Comment by EricBishton** [comment]
This was released with version 1.3.
