### ISSUE TITLE
[ERROR] IntelliJ IDEA 2019.2.3 

### ISSUE THREAD

**Issue by angelhdz** [HaxeFoundation/intellij-haxe#977]
![image](https://user-images.githubusercontent.com/10191085/70743300-dc7d8400-1cf5-11ea-97d8-6cf5bd5d7e5b.png)

**Comment by EricBishton** [comment]
Dup of #971 .  I did a fix in 12bc205 that fixes the problem.  You can pick up a test build at https://github.com/EricBishton/intellij-haxe/releases/tag/Post1.2TestBuild.2.

**Comment by angelhdz** [comment]
![image](https://user-images.githubusercontent.com/10191085/70838557-3dcd5200-1ddf-11ea-9b5f-2c3e3d0c30ba.png)

**Comment by angelhdz** [comment]
![image](https://user-images.githubusercontent.com/10191085/70838814-643fbd00-1de0-11ea-85f3-affd103a88bb.png)

Added neko and haxelib executables and nothing.

**Comment by angelhdz** [comment]
Ok, deleting the Haxe SDK and reading it, now shows the Haxe SDK version, and those errors are gone, but now I'm back at the first error:

`Information:Working path: C:/Users/Angel/IdeaProjects/TestHaxe/Test
Information:Output path: C:/Users/Angel/IdeaProjects/TestHaxe/out
Information:Output file: 
Information:Running command: C:/HaxeToolkit/haxe/haxelib.exe run lime update C:/Users/Angel/IdeaProjects/TestHaxe/Test/src/app-descriptor.xml air -verbose -debug -Ddebug
Information:
Information:_/\\\\\\______________________________________________
Information:_\////\\\______________________________________________
Information:_____\/\\\_____/\\\_____________________________________
Information:______\/\\\____\///_____/\\\\\__/\\\\\_______/\\\\\\\\___
Information:_______\/\\\_____/\\\__/\\\///\\\\\///\\\___/\\\/////\\\__
Information:________\/\\\____\/\\\_\/\\\_\//\\\__\/\\\__/\\\\\\\\\\\___
Information:_________\/\\\____\/\\\_\/\\\__\/\\\__\/\\\_\//\\///////____
Information:________/\\\\\\\\\_\/\\\_\/\\\__\/\\\__\/\\\__\//\\\\\\\\\\__
Information:________\/////////__\///__\///___\///___\///____\//////////___
Information:Lime Command-Line Tools (7.6.3)
Information:Initializing project...
Information:Using project file: C:/Users/Angel/IdeaProjects/TestHaxe/Test/src/app-descriptor.xml
Information:Reading Lime config: C:\Users\Angel\.lime\config.xml
Information:Running command: UPDATE
Information: - Embedding asset: (MANIFEST) manifest/default.json
Information:Warning: Could not find template file: default/icon.svg
Information:Warning: Could not find icon path: null
Information:Warning: Could not find template file: haxe
Information:Warning: Could not find template file: air/hxml
Information:Warning: Could not find template file: air/template
Information:Called from ? line 1
Information:Called from CommandLineTools.hx line 1895
Information:Called from CommandLineTools.hx line 22
Information:Called from a C function
Information:Called from CommandLineTools.hx line 126
Information:Called from CommandLineTools.hx line 641
Information:Called from lime/tools/PlatformTarget.hx line 98
Information:Called from AIRPlatform.hx line 281
Information:Called from /usr/share/haxe/std/neko/_std/sys/io/File.hx line 30
Information:Uncaught exception - [file_contents,bin/air/haxe/debug.hxml]
Information:No additional error information available.
Information:Running command: C:/HaxeToolkit/haxe/haxelib.exe run lime build C:/Users/Angel/IdeaProjects/TestHaxe/Test/src/app-descriptor.xml air -verbose -debug -Ddebug
Information:12/13/2019 7:46 PM - Build completed with 2 errors and 0 warnings in 1 s 588 ms
Error: (Command exited with an error code) 1
Error:Compilation failed`

**Comment by angelhdz** [comment]
### Update

New errors are related to OpenFL. I think I can debug those now. Thank you!

**Comment by EricBishton** [comment]
Glad you figured it out!
