### ISSUE TITLE
Can't install SDK - IntelliJ 2019.1 - Mac

### ISSUE THREAD

**Issue by douglasmccarroll** [HaxeFoundation/intellij-haxe#979]
Hi,

I've downloaded and installed the Haxe toolkit on my Mac. When I try to install it (/usr/local/lib/haxe/) as an SDK in IntelliJ 2019.1 it appears to install, but displays as "Haxe NA".

[Issue 970](https://github.com/HaxeFoundation/intellij-haxe/issues/970) says "If the SDK is "Haxe NA" it means that the plugin couldn't find (or didn't have permissions to run) the Haxe executable" so, clearly, something is amiss.

I'm an experienced programmer but new to Haxe. What should I do next?

Thanks,

Douglas

**Comment by EricBishton** [comment]
Hi Douglas,

If the haxe executable was not found, then its directory (and those of haxelib and neko, if different) needs to be added to your system path.  If you only add it to your login script (e.g. .bashrc), then toolkit will only be available if you start idea from the command line.  There are several recipes available for how to add directories to the system path on the Mac.  Unfortunately, it changes with the OS version. This discussion may be able to help you: https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite

Let me know how it goes!

**Comment by tsal** [comment]
I just did a fresh install of IDEA 2019.3.3 and I'm getting the same issue.  I'm fairly certain it isn't a path issue, as the terminal within IDEA can find it:

```
$ haxe --version
4.0.5
```

**Comment by m0rkeulv** [comment]
Version 1.4.7 now checks some default paths for linux and macOS, perhaps this  remedies this issue ?

**Comment by CanIGetaPR** [comment]
Suggesting this issue is closed, lacking feedback from the issue author and a new issue created if the problem persists on updated plugin and IDE versions.
