### ISSUE TITLE
Assigning EnumValue to EnumValue is marked as error

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/intellij-haxe#982]
https://try.haxe.org/#66B86

![image](https://user-images.githubusercontent.com/1607138/72792494-cf7f7900-3c41-11ea-9556-4ccdb373b4ec.png)

**Comment by m0rkeulv** [comment]
should have been fixed in https://github.com/HaxeFoundation/intellij-haxe/pull/1026 and should work on the Develop branch.

**Comment by EricBishton** [comment]
Will be in 1.4 release.
