### ISSUE TITLE
Didn't find possibility to add blank line after package and import in code style

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/intellij-haxe#984]

**Comment by EricBishton** [comment]
I agree that this should be available on the Haxe screen.  It is currently hard coded.  HaxeSpacingProcessor.getSpacing(), line 95.

**Comment by m0rkeulv** [comment]
Closing this one as this was added in 1.4.39
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/fada3a0d-032a-40ea-a3f3-1cd78cf9a14e)
