### ISSUE TITLE
Haxe4 : Support `final x` at expression-level

### ISSUE THREAD

**Issue by kaikoga** [HaxeFoundation/intellij-haxe#985]
Continuation of #670 and #864.

Haxe manual: https://haxe.org/manual/expression-var.html

http://try-haxe.mrcdk.com/#b6fAD

Things like `final i = 1;` to declare readonly local variables and `case Pattern(final x)`to capture variables in pattern matching are now valid, which is implemented in HaxeFoundation/haxe#7398.

**Comment by EricBishton** [comment]
Fixed with PR #1000
