### ISSUE TITLE
Why Does Gradle Download IJIdea When I Have It?

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#987]
Why Does Gradle Download IJIdea When I Have It?

I'm using `gradlew.bat clean build verifyPlugin -PtargetVersion=2019.3.3` because that's the version I have installed 
![image](https://user-images.githubusercontent.com/45294513/74851834-c8fc2400-5309-11ea-8bae-bc3f849988e0.png)
yet, the build process is trying to re-download the entire IDE. 

```
> Configure project :
Target set to IDEA 2019.3.3
Including java plugin for version >= 2019.2
Including java plugin for version >= 2019.2
Including java plugin for version >= 2019.2
Including java plugin for version >= 2019.2
<-------------> 0% CONFIGURING [1m 2s]
> IDLE
> root project > Resolve files of :detachedConfiguration1 > ideaIU-2019.3.3.zip > 89.27 MB/673.53 MB downloaded
```

**Comment by m0rkeulv** [comment]
It downloads the configured version and sets up a "sandbox" where you can test your plugin without affecting your current installation. this is is also useful when you need to test or fix something in a version that you currently don't have installed.  

a typical use case  would be to test  if the plugin  can be compiled for and works with the latest EAP version,  like the 2020.1 version that is hopefully going to be released soon.
