### ISSUE TITLE
IntelliJ hangs when I try to list override methods CTRL + O

### ISSUE THREAD

**Issue by develm** [HaxeFoundation/intellij-haxe#990]
Hello,

Whenever I try to list methods available for override with **CTRL + O** IntelliJ takes couple of minutes to list available methods. During this time the IDE is completely unresponsive.

IDE: IntelliJ 2019.3.4
haxe Toolkit Support: 1.2
OS: Fedora 31 5.5.13-200.fc31.x86_64 (Did not work on previous version either)
JDK: openjdk 11.0.6 2020-01-14 LTS

format: [3.5.0]
hashlink: [0.1.0]
heaps: [1.7.0]
hldx: [1.10.0]
hlopenal: [1.5.0]
hlsdl: [1.10.0]

I added library sources and classes from ~/haxelib/heaps

Steps to reproduce:
1. checkout example project: https://github.com/HaxeFoundation/intellij-haxe/tree/master/ExampleProjects/HeapsOnHLExample
2. Enter MyApp.hx
3. click CTRL + O (or any shortcut to override methods)

**Comment by develm** [comment]
Same thing happens on Android Studio 3.6.2

**Comment by EricBishton** [comment]
Verified on current development branch.  FWIW, things are running, just slowly.  The actual candidates are being found rather quickly, but trying to create the "presentation" strings is causing many (many (many)) other source files to be parsed.

**Comment by EricBishton** [comment]
Fixed by PR#1008
